# Generated by Django 5.2.16 on 2026-09-23 01:07

import concepts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exercises', '0013_exercise_material_link'),
        ('taxonomy', '0006_branch_proposed_at_branch_proposed_by_branch_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='concepts', to='taxonomy.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts_created', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='concepts', to='exercises.tag')),
            ],
            options={
                'ordering': ['-updated_at', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ConceptArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('early_years', 'Early years (0–6, via an adult)'), ('primary', 'Primary school (6–12)'), ('secondary', 'Secondary school (12–19)'), ('university', 'University'), ('adult', 'Adult learners'), ('senior', 'Seniors'), ('all', 'Everyone')], db_index=True, default='university', max_length=12)),
                ('locale', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pinned', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('auto_hidden_at', models.DateTimeField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='concepts.concept')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['concept', 'audience', 'locale', '-pinned', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConceptAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Picture'), ('pdf', 'PDF')], max_length=5)),
                ('file', models.FileField(upload_to=concepts.models.asset_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('relation', models.CharField(choices=[('related', 'Related'), ('prerequisite', 'Prerequisite')], default='related', max_length=12)),
                ('origin', models.CharField(choices=[('manual', 'Added by somebody'), ('body', 'From the text')], default='manual', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='concepts.concept')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['relation', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='concepts_co_content_9aa4c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('concept', 'content_type', 'object_id'), name='one_link_per_target')],
            },
        ),
        migrations.CreateModel(
            name='ConceptRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Waiting for review'), ('published', 'Published'), ('superseded', 'Superseded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('search_text', models.TextField(blank=True, editable=False)),
                ('change_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='concepts.conceptarticle')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='concepts.conceptrevision')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_revisions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['article', 'number'],
                'constraints': [models.UniqueConstraint(fields=('article', 'number'), name='unique_revision_number_per_article'), models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('article',), name='one_published_revision_per_article')],
            },
        ),
    ]
