# Generated by Django 5.2.16 on 2026-08-02 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0002_subtopic_subtopictranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=32)),
                ('country', models.CharField(default='PL', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('email_domains', models.JSONField(default=list)),
                ('grade_scale', models.CharField(choices=[('polish_2_5', 'Polish 2.0–5.0'), ('ects_letter', 'ECTS letter')], default='polish_2_5', max_length=20)),
                ('usos_base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EducationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_school_name', models.CharField(blank=True, max_length=200)),
                ('verification', models.CharField(choices=[('self_declared', 'Self-declared'), ('school_email', 'Institutional email'), ('usos', 'USOS')], default='self_declared', max_length=20)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('student', 'Current student'), ('alumnus', 'Alumnus'), ('staff', 'Staff')], default='unknown', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_via', models.CharField(blank=True, max_length=20)),
                ('programme', models.CharField(blank=True, max_length=200)),
                ('study_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('usos_user_id', models.CharField(blank=True, max_length=64)),
                ('usos_student_number', models.CharField(blank=True, max_length=64)),
                ('usos_connected_at', models.DateTimeField(blank=True, null=True)),
                ('usos_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('usos_scopes', models.JSONField(blank=True, default=list)),
                ('share_school', models.BooleanField(default=False)),
                ('share_diploma', models.BooleanField(default=False)),
                ('share_grades', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='identity.school')),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('programme', models.CharField(blank=True, max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=16)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='identity.educationprofile')),
            ],
            options={
                'ordering': ['-issued_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('term', models.CharField(blank=True, max_length=32)),
                ('ects', models.PositiveSmallIntegerField(default=0)),
                ('value', models.CharField(max_length=16)),
                ('scale', models.CharField(choices=[('polish_2_5', 'Polish 2.0–5.0'), ('ects_letter', 'ECTS letter')], default='polish_2_5', max_length=20)),
                ('matched_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_grades', to='taxonomy.course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='identity.educationprofile')),
            ],
            options={
                'ordering': ['term', 'name'],
            },
        ),
    ]
