# Generated by Django 5.2.16 on 2026-07-25 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_notify_on_comment_reply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('paypal', 'PayPal'), ('payu', 'PayU'), ('blik', 'BLIK'), ('card', 'Card payment'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('buy_me_a_coffee', 'Buy Me a Coffee'), ('ko_fi', 'Ko-fi'), ('patreon', 'Patreon'), ('github_sponsors', 'GitHub Sponsors'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_links', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
