# Generated by Django 5.2.16 on 2026-07-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_donationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='muted_notification_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
