# Generated by Django 5.2.16 on 2026-07-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_muted_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='offers_tutoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='tutoring_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
