# Generated by Django 5.2.16 on 2026-07-31 09:27

import accounts.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_offers_tutoring_profile_tutoring_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[accounts.avatar.validate_avatar_file]),
        ),
    ]
