# Generated by Django 5.2.16 on 2026-08-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_on_course_activity',
            field=models.BooleanField(default=True),
        ),
    ]
