# Generated by Django 5.2.16 on 2026-08-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_notify_on_course_activity'),
        ('taxonomy', '0002_subtopic_subtopictranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('study', 'Studies'), ('work', 'Work'), ('teaching', 'Teaching'), ('project', 'Project'), ('other', 'Other')], default='other', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', '-started_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('learning', 'Learning'), ('comfortable', 'Comfortable'), ('teaching', 'Could teach it')], default='comfortable', max_length=12)),
                ('evidence', models.CharField(choices=[('self_declared', 'Self-declared'), ('coursework', 'Passed the course here'), ('registry', 'Confirmed by the university registry')], default='self_declared', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_skills', to='taxonomy.course')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_skills', to='taxonomy.field')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'label'), name='unique_skill_label_per_profile')],
            },
        ),
    ]
