# Generated by Django 5.2.16 on 2026-08-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_on_booking',
            field=models.BooleanField(default=True),
        ),
    ]
