# Generated by Django 5.2.16 on 2026-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_notify_on_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_format',
            field=models.CharField(choices=[('24h', '24-hour'), ('12h', '12-hour (AM/PM)')], default='24h', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='week_starts_on',
            field=models.CharField(choices=[('monday', 'Monday'), ('sunday', 'Sunday')], default='monday', max_length=8),
        ),
    ]
