# Generated by Django 5.2.16 on 2026-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_time_format_profile_week_starts_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_on_event',
            field=models.BooleanField(default=True),
        ),
    ]
