# Generated by Django 5.2.16 on 2026-08-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_notify_on_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_courses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
