# Generated by Django 5.2.16 on 2026-08-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_max_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillentry',
            old_name='course',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='skillentry',
            old_name='field',
            new_name='discipline',
        ),
    ]
