# Generated by Django 5.2.16 on 2026-08-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_material_upload_quota_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='save_menu_layout',
            field=models.CharField(choices=[('beside', 'Courses beside the sets'), ('above', 'Courses above the sets')], default='beside', max_length=8),
        ),
    ]
