# Generated by Django 5.2.16 on 2026-08-08 11:39
#
# NUMBERED 0017 ON PURPOSE, AND ITS DEPENDENCY IS THE THING TO CHECK WHEN MERGING.
# A `0016_..._save_menu_layout` is in flight on another branch, so this takes the number after it
# rather than colliding with it. It cannot yet DEPEND on a file that does not exist in this branch, so
# it depends on 0015 — which means that once both land there are two leaf nodes and
# `makemigrations --check` will say so. The fix is one line: point `dependencies` at 0016 instead
# (nothing here touches `Profile`, so the two are genuinely independent and the order does not
# matter). A `makemigrations --merge` would also work and is the wrong answer — it leaves a merge
# migration in the tree for what is really a stale one-line dependency.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_material_upload_quota_bytes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', '-issued_on', 'id'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'title', 'issuer'), name='unique_certificate_per_profile')],
            },
        ),
    ]
