# Generated by Django 5.2.16 on 2026-08-08 11:39
#
# Written on a branch where `0016_profile_save_menu_layout` did not yet exist, so it was cut against
# 0015 and left a note saying to repoint it on merge. Done: it depends on 0016 now, which is the
# one-line fix rather than a `makemigrations --merge`, since the two are genuinely independent —
# nothing here touches `Profile` — and a merge migration would leave a permanent artefact in the
# tree for what was a stale dependency.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_save_menu_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', '-issued_on', 'id'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'title', 'issuer'), name='unique_certificate_per_profile')],
            },
        ),
    ]
