# Generated by Django 5.2.16 on 2026-08-26 14:25

from django.db import migrations, models
from django.db.models import Count, Q


def backfill(apps, schema_editor):
    """Every existing profile starts with the true numbers rather than 0 — the counters are only
    maintained from here on, so the rows that predate them have to be counted once."""
    Exercise = apps.get_model('exercises', 'Exercise')
    Profile = apps.get_model('accounts', 'Profile')
    totals = (
        Exercise.objects.filter(submitted_by__isnull=False)
        .order_by()
        .values('submitted_by_id')
        .annotate(
            # Not `published=Count(...)`: an annotation named after the field shadows it, so the
            # second filter would have read the first COUNT rather than the column.
            n_published=Count('pk', filter=Q(published=True)),
            n_private=Count('pk', filter=Q(published=False)),
        )
    )
    for row in totals:
        Profile.objects.filter(user_id=row['submitted_by_id']).update(
            exercises_published_count=row['n_published'],
            exercises_private_count=row['n_private'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_certificate'),
        ('exercises', '__latest__'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exercises_private_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='exercises_published_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
