# Generated by Django 5.2.16 on 2026-08-26 15:33

from django.db import migrations, models
from django.db.models import Count, Q


def backfill(apps, schema_editor):
    Material = apps.get_model('materials', 'Material')
    Profile = apps.get_model('accounts', 'Profile')
    totals = (
        Material.objects.filter(submitted_by__isnull=False)
        .order_by()
        .values('submitted_by_id')
        .annotate(
            n_published=Count('pk', filter=Q(published=True)),
            n_private=Count('pk', filter=Q(published=False)),
        )
    )
    for row in totals:
        Profile.objects.filter(user_id=row['submitted_by_id']).update(
            materials_published_count=row['n_published'],
            materials_private_count=row['n_private'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_exercise_counts'),
        ('materials', '__latest__'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='materials_private_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='materials_published_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
