# Generated by Django 5.2.16 on 2026-09-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_material_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audience_filter',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
