# Generated by Django 5.2.16 on 2026-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_guardianship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content_locales',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
