# Generated by Django 5.2.16 on 2026-09-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='editor_mode',
            field=models.CharField(choices=[('rich', 'Editor'), ('source', 'Source')], default='source', max_length=6),
        ),
    ]
