# Generated by Django 5.2.16 on 2026-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_editor_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='text_size',
            field=models.CharField(choices=[('normal', 'Normal'), ('large', 'Large'), ('larger', 'Larger')], default='normal', max_length=6),
        ),
    ]
