# Generated by Django 5.2.16 on 2026-08-03 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0002_subtopic_subtopictranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('location_kind', models.CharField(choices=[('onsite', 'In a physical place'), ('online', 'Online'), ('hybrid', 'Both — a room, and a link')], default='onsite', max_length=8)),
                ('location_text', models.CharField(blank=True, max_length=300)),
                ('online_url', models.URLField(blank=True, max_length=500)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('language', models.CharField(default='pl', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='taxonomy.field')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, related_name='events', to='taxonomy.course')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Going'), ('not_going', 'Not going')], default='going', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'starts_at'], name='events_even_status_5c3d55_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('event', 'attendee'), name='unique_event_attendance'),
        ),
    ]
