# Generated by Django 5.2.16 on 2026-08-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='field',
            new_name='discipline',
        ),
    ]
