# Generated by Django 5.2.16 on 2026-09-09 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seat_hosts(apps, schema_editor):
    """Every existing event's host becomes its organiser row — the invariant Event.save() keeps
    for new rows, applied once to the ones that predate EventStaff."""
    Event = apps.get_model('events', 'Event')
    EventStaff = apps.get_model('events', 'EventStaff')
    for event in Event.objects.all().only('id', 'host_id'):
        EventStaff.objects.get_or_create(event_id=event.id, user_id=event.host_id, defaults={'role': 'organiser'})


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_audience'),
        ('exercises', '0012_audience'),
        ('materials', '0016_audience'),
        ('study', '0004_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('talk', 'Talk'), ('workshop', 'Workshop'), ('poster', 'Poster session'), ('break', 'Break'), ('social', 'Social'), ('other', 'Other')], default='talk', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('location_text', models.CharField(blank=True, max_length=300)),
                ('online_url', models.URLField(blank=True, max_length=500)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event')),
            ],
            options={
                'ordering': ['starts_at', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaking_at', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('colour', models.CharField(blank=True, max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='events.track'),
        ),
        migrations.CreateModel(
            name='EventStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('organiser', 'Organiser'), ('reviewer', 'Reviewer'), ('volunteer', 'Volunteer')], default='organiser', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_staff_added', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_staff_per_event')],
            },
        ),
        migrations.CreateModel(
            name='SessionBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='events.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'session'), name='unique_bookmark_per_session')],
            },
        ),
        migrations.CreateModel(
            name='SessionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('role', models.CharField(choices=[('prepare', 'Read or try before'), ('live', 'Worked through in the room'), ('homework', 'Afterwards, on your own'), ('slides', 'Slides'), ('recording', 'Recording'), ('solutions', 'Solutions'), ('other', 'Related')], default='other', max_length=10)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='exercises.exercise')),
                ('exercise_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='study.exerciseset')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='materials.material')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.session')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('exercise__isnull', True), ('exercise_set__isnull', True), ('material__isnull', False), ('url', '')), models.Q(('exercise__isnull', False), ('exercise_set__isnull', True), ('material__isnull', True), ('url', '')), models.Q(('exercise__isnull', True), ('exercise_set__isnull', False), ('material__isnull', True), ('url', '')), models.Q(('exercise__isnull', True), ('exercise_set__isnull', True), ('material__isnull', True), models.Q(('url', ''), _negated=True)), _connector='OR'), name='session_link_exactly_one_target')],
            },
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_track_name_per_event'),
        ),
        migrations.RunPython(seat_hosts, migrations.RunPython.noop),
    ]
