# Generated by Django 5.2.16 on 2026-09-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='runs_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
