# Generated by Django 5.2.16 on 2026-09-09 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_runs_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_mode',
            field=models.CharField(choices=[('rsvp', 'Anyone may register, immediately'), ('approval', 'The organiser confirms each registration'), ('form', 'A registration form, confirmed immediately')], default='rsvp', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='show_attendees_publicly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_checkins_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='promotion_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='waitlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='status',
            field=models.CharField(choices=[('going', 'Going'), ('not_going', 'Not going'), ('pending', 'Awaiting approval'), ('waitlisted', 'On the waiting list'), ('promoted', 'Seat offered — awaiting confirmation'), ('expired', 'Offer expired')], default='going', max_length=10),
        ),
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('text', 'Short text'), ('long_text', 'Longer text'), ('choice', 'One of a list'), ('multi', 'Any of a list'), ('checkbox', 'Yes / no')], default='text', max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_fields', to='events.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_registrations', to='events.eventattendance')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.session')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'attendance'), name='one_seat_per_session')],
            },
        ),
    ]
