# Generated by Django 5.2.16 on 2026-09-09 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cfp_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cfp_open',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('talk', 'Talk'), ('workshop', 'Workshop'), ('poster', 'Poster'), ('other', 'Other')], default='talk', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('early_years', 'Early years (0–6, via an adult)'), ('primary', 'Primary school (6–12)'), ('secondary', 'Secondary school (12–19)'), ('university', 'University'), ('adult', 'Adult learners'), ('senior', 'Seniors'), ('all', 'Everyone')], default='university', max_length=12)),
                ('co_authors', models.JSONField(blank=True, default=list)),
                ('notes_to_organiser', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('withdrawn', 'Withdrawn')], default='draft', max_length=12)),
                ('reason_code', models.CharField(blank=True, choices=[('out_of_scope', 'Out of scope for this event'), ('duplicate', 'Duplicates another proposal'), ('no_room', 'No room in the programme'), ('needs_revision', 'Needs revision'), ('other', 'Other')], max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_decided', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='events.event')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='events.session')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
    ]
