# Generated by Django 5.2.16 on 2026-09-23 14:55
"""The export log, and nothing else — CONFERENCE-BRIEF.md §3.G, step G of seven built in parallel.

Step D (`conf/d-tickets`) also writes an `events` migration numbered `0011`. That is expected and
was planned for: this file deliberately contains **one `CreateModel` and no other operation**, and
the model it creates touches nothing D touches. Whoever integrates the branches renumbers this one
to `0012_exportlog`, changes `dependencies` to D's `0011_tickets`, and is finished — there is no
field to reconcile and no data migration to re-order.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_contributions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('full_csv', 'Full registration CSV'), ('door_list', 'Door list CSV')], max_length=16)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
