# Tickets and scanning (CONFERENCE-BRIEF.md §3.D) — the ONE `events` schema change the seven
# parallel conference branches are allowed (§4 rule 1). Three things: an opaque ticket token on the
# attendance row (unique, null until the row first holds a seat — many NULLs in a unique column is
# what makes "most rows have no ticket" expressible), its `checked_out_at` counterpart so that
# "inside" is derived from a pair of timestamps rather than a third boolean, and the append-only
# `ScanEvent` log, which records the refusals as well as the admissions.
#
# Nothing is backfilled. An existing `going` row gets its ticket the next time the registration
# engine touches it or its owner opens `my-ticket`, which `events/scanning.ensure_ticket` states as
# its own honest limit — a data migration minting a few hundred tokens would have to be re-run for
# every row created between it and this deploy anyway.
# Generated by Django 5.2.16 on 2026-09-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_exportlog'),  # renumbered at integration: G's 0011 landed first
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='ticket_token',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_seen', models.CharField(blank=True, max_length=64)),
                ('direction', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], default='entry', max_length=5)),
                ('result', models.CharField(choices=[('admitted', 'Admitted'), ('already_in', 'Nothing changed — already on that side of the door'), ('not_going', 'Not on the going list'), ('unknown', 'No such ticket for this event'), ('exited', 'Recorded leaving'), ('collision', 'The same ticket entered twice in one sync — possibly passed back')], max_length=10)),
                ('client_nonce', models.CharField(max_length=64, unique=True)),
                ('client_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device_label', models.CharField(blank=True, max_length=60)),
                ('is_offline_sync', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='events.eventattendance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='events.event')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_scans_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['event', 'received_at'], name='events_scan_event_i_9fbb9f_idx')],
            },
        ),
    ]
