# Generated by Django 5.2.16 on 2026-07-25 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_exercise_auto_hidden_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('submission_approved', 'Exercise submission approved'), ('submission_rejected', 'Exercise submission rejected'), ('edit_suggestion_approved', 'Edit suggestion approved'), ('edit_suggestion_rejected', 'Edit suggestion rejected'), ('translation_approved', 'Translation approved'), ('translation_rejected', 'Translation rejected'), ('comment_reply', 'Reply to your comment'), ('content_auto_hidden', 'Content auto-hidden by community reports'), ('content_restored', 'Content restored by a moderator'), ('content_removed', 'Content removed by a moderator')], max_length=32)),
                ('target_label', models.CharField(blank=True, max_length=300)),
                ('note', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.exercise')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
