# Generated by Django 5.2.16 on 2026-07-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_tags_alter_material_type'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('submission_approved', 'Exercise submission approved'), ('submission_rejected', 'Exercise submission rejected'), ('edit_suggestion_approved', 'Edit suggestion approved'), ('edit_suggestion_rejected', 'Edit suggestion rejected'), ('translation_approved', 'Translation approved'), ('translation_rejected', 'Translation rejected'), ('comment_reply', 'Reply to your comment'), ('content_auto_hidden', 'Content auto-hidden by community reports'), ('content_restored', 'Content restored by a moderator'), ('content_removed', 'Content removed by a moderator'), ('new_tagged_content', 'New content tagged with a tag you follow')], max_length=32),
        ),
    ]
