# Generated by Django 5.2.16 on 2026-08-02 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_enrollment_notify_taughtcourse_announce_new_lessons_and_more'),
        ('notifications', '0002_notification_material_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='taught_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classroom.taughtcourse'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('submission_approved', 'Exercise submission approved'), ('submission_rejected', 'Exercise submission rejected'), ('edit_suggestion_approved', 'Edit suggestion approved'), ('edit_suggestion_rejected', 'Edit suggestion rejected'), ('translation_approved', 'Translation approved'), ('translation_rejected', 'Translation rejected'), ('comment_reply', 'Reply to your comment'), ('content_auto_hidden', 'Content auto-hidden by community reports'), ('content_restored', 'Content restored by a moderator'), ('content_removed', 'Content removed by a moderator'), ('new_tagged_content', 'New content tagged with a tag you follow'), ('course_enrollment_requested', 'Somebody asked to join your course'), ('course_enrollment_approved', 'You were let into a course'), ('course_enrollment_declined', 'Your request to join was declined'), ('course_removed', 'You were removed from a course'), ('course_new_lesson', 'A new lesson in a course you are taking'), ('course_new_post', 'A new post in a course discussion')], max_length=32),
        ),
    ]
