# Generated by Django 5.2.16 on 2026-08-03 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('submission_approved', 'Exercise submission approved'), ('submission_rejected', 'Exercise submission rejected'), ('edit_suggestion_approved', 'Edit suggestion approved'), ('edit_suggestion_rejected', 'Edit suggestion rejected'), ('translation_approved', 'Translation approved'), ('translation_rejected', 'Translation rejected'), ('comment_reply', 'Reply to your comment'), ('content_auto_hidden', 'Content auto-hidden by community reports'), ('content_restored', 'Content restored by a moderator'), ('content_removed', 'Content removed by a moderator'), ('new_tagged_content', 'New content tagged with a tag you follow'), ('course_enrollment_requested', 'Somebody asked to join your course'), ('course_enrollment_approved', 'You were let into a course'), ('course_enrollment_declined', 'Your request to join was declined'), ('course_removed', 'You were removed from a course'), ('course_new_lesson', 'A new lesson in a course you are taking'), ('course_new_post', 'A new post in a course discussion'), ('course_contribution_submitted', 'Somebody offered content to a course you run'), ('course_contribution_approved', 'Your contribution was accepted'), ('course_contribution_rejected', 'Your contribution was not accepted'), ('course_staff_added', 'You were made a member of a course team'), ('course_invite_used', 'Somebody used your invite link'), ('booking_requested', 'Somebody asked to book a session with you'), ('booking_confirmed', 'Your booking was confirmed'), ('booking_declined', 'Your booking request was declined'), ('booking_cancelled', 'A booking was cancelled'), ('event_attendance', 'Somebody is coming to your event'), ('event_updated', 'An event you are going to has changed'), ('event_cancelled', 'An event you were going to was called off')], max_length=32),
        ),
    ]
