# Generated by Django 5.2.16 on 2026-09-20 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coauthoring', '0001_initial'),
        ('notifications', '0018_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='material_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coauthoring.materialproject'),
        ),
    ]
