"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x#=tushw$te2p$ti6@wo5(6o40kvc+k_n6s7x212pn9c0p_9-s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third-party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    # edmat apps — see CLAUDE.md Section 9 for the model/app split
    'taxonomy',
    'exercises',
    'materials',
    'community',
    'moderation',
    'study',
    'accounts',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Real, found-during-testing need, not a defensive default: SQLite only ever allows ONE
        # writer at a time, and Python's own sqlite3 module falls back to a 5-SECOND busy timeout
        # when nothing else is configured — genuinely too short under real concurrent write load.
        # A real multi-moderator concurrency test (two moderators approving different submissions
        # for the same course at nearly the same instant) reproduced `sqlite3.OperationalError:
        # database is locked` even for a single, tiny write statement, confirmed via the real dev
        # server's own log, not a guess. Raising this to 20s doesn't fix the underlying single-writer
        # limitation (that's inherent to SQLite, not this setting) — it just makes a genuinely
        # concurrent write WAIT for its turn instead of failing outright, which is the correct
        # tradeoff for this app's real write volume (a moderation queue, not a high-frequency system).
        'OPTIONS': {'timeout': 20},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# User-uploaded files (Material PDFs, Section 9) — served by Django's dev server only while DEBUG is
# on (config/urls.py wires static() for this); a real deployment would front this with a real media
# host, not attempted here (mock-era honesty, matching the rest of this project's own conventions).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Material submission safety (materials/validators.py) — real content-type sniffing always runs
# regardless of these settings; a genuine ClamAV scan is attempted too, but this sandboxed dev
# environment has no ClamAV daemon installed (confirmed: no clamscan/clamdscan/freshclam binary
# anywhere, and no root access to install one — the same constraint CLAUDE.md's own venv note
# already records for a different tool). MATERIAL_SCAN_REQUIRED=False here is this environment's
# own honest default (an upload proceeds with the scan recorded as skipped, not silently treated as
# "scanned and clean") — a real deployment that actually runs ClamAV should set this True, which
# makes an unreachable scanner a hard rejection instead of a graceful skip.
MATERIAL_SCAN_REQUIRED = False
CLAMD_UNIX_SOCKET = '/var/run/clamav/clamd.ctl'
CLAMD_HOST = 'localhost'
CLAMD_PORT = 3310

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# ⚠️ Auth mechanism (CLAUDE.md Section 18, item 1) — resolved for this prototype as DRF's built-in
# TokenAuthentication: the "simple" option that section itself named, appropriate for a local/
# prototype deployment with no SSO requirement (Section 4). SessionAuthentication stays enabled too
# so the browsable API and the Django admin both keep working during development.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Phase 3 — deliberately no default pagination. Every real list endpoint the frontend actually
    # calls is already bounded by construction (course-scoped exercise/material lists, a `limit=`
    # top-rated/recent query, a moderator's own pending queue, one user's own exercise sets) — none
    # of them are the "browse an unbounded feed" shape pagination exists for. Turning it on here
    # would have meant every list response coming back wrapped in a {count,next,previous,results}
    # envelope, which the handful of custom @action endpoints (exercises/{id}/reviews/, /comments/,
    # /translations/, fields/{slug}/courses/, courses/{slug}/exercises/) never used anyway, since
    # each builds its own plain Response(serializer.data) — leaving pagination on globally would
    # just have meant a real, avoidable inconsistency between the two endpoint styles.
    'DEFAULT_PAGINATION_CLASS': None,
}

# CORS — the SvelteKit dev server (Phase 1 frontend) runs on a separate origin/port; this is what
# lets it call the API directly during Phase 3 wiring. Tightened to a real allowlist rather than
# CORS_ALLOW_ALL_ORIGINS, since credentials (the auth token) will ride along with these requests.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
]
CORS_ALLOW_CREDENTIALS = True
