"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _split_env_list(name: str, default: tuple[str, ...] = ()) -> list[str]:
    """A comma-separated env var -> list, falling back to `default` (usually empty) when unset —
    the one place every one of the env-driven list settings below (ALLOWED_HOSTS,
    CSRF_TRUSTED_ORIGINS, the extra CORS origins) reads from, so a real deployment sets these once
    in /etc/apache2/envvars (see deploy/DEPLOYMENT.md) without needing a settings.py edit at all,
    while local dev (nothing set) gets back exactly the empty/default list it always had."""
    raw = os.environ.get(name)
    if not raw:
        return list(default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! Read from the environment (a
# real deployment sets `DJANGO_SECRET_KEY` in /etc/apache2/envvars — sourced by apache2.service on
# every start, which is what makes it visible to a mod_wsgi daemon process; see
# deploy/DEPLOYMENT.md) rather than committed to a file in this repo. The fallback below is the
# literal key `django-admin startproject` originally generated — fine for local dev (never
# reachable from outside this machine), never acceptable for a real deployment, which is exactly
# why this is read from the environment rather than hardcoded unconditionally.
INSECURE_DEV_SECRET_KEY = 'django-insecure-x#=tushw$te2p$ti6@wo5(6o40kvc+k_n6s7x212pn9c0p_9-s'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', INSECURE_DEV_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production! Also read from the environment —
# defaults to True (the historical dev behavior) so nothing changes for local `manage.py runserver`
# unless `DJANGO_DEBUG=False` is explicitly set server-side, once Apache is confirmed serving
# /static/ and /media/ directly (Django's own dev-time auto-serving of both only runs while DEBUG
# is True).
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# --- Fail loudly rather than fail open ----------------------------------------------------------
#
# Every production setting in this file is read from the environment, which is the right design —
# but it means the whole security posture rests on `/etc/apache2/envvars` actually being sourced.
# The failure mode if it isn't is silent and severe: `DJANGO_DEBUG` unset defaults to `True` and
# `DJANGO_SECRET_KEY` unset falls back to the key committed a few lines above, so a typo in that
# file, an `apache2ctl` invocation that doesn't source it, or a mod_wsgi daemon started without the
# environment would bring the SITE UP — publicly, on the real domain — serving full tracebacks
# (with settings, queries and paths in them) and signing sessions/CSRF tokens with a key published
# in this repository. Nothing would look wrong; it would just quietly be a different, far weaker
# site than the one that was deployed.
#
# So the two genuinely dangerous combinations refuse to boot at all. A `mod_wsgi` process that
# raises here returns 500 for every request, which is loud, obvious, immediately diagnosable from
# the Apache error log, and — the actual point — strictly safer than serving the site insecurely.
# Local dev is completely unaffected: it sets neither variable, keeps DEBUG=True, and never reaches
# either branch.
if not DEBUG and SECRET_KEY == INSECURE_DEV_SECRET_KEY:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY is not set, so SECRET_KEY fell back to the insecure development key '
        'that is committed to this repository — with DEBUG=False this is a real deployment, and '
        'that key is public. Refusing to start. Generate one with '
        '`python -c "from django.core.management.utils import get_random_secret_key as k; print(k())"` '
        'and export DJANGO_SECRET_KEY in /etc/apache2/envvars (see deploy/DEPLOYMENT.md step 6).'
    )

# The mirror-image check (DEBUG=True together with a real ALLOWED_HOSTS) lives just below
# ALLOWED_HOSTS itself, since it can't run until that setting has actually been read.

# Empty by default (Django's own documented behavior: DEBUG=True + ALLOWED_HOSTS=[] implicitly
# allows localhost/127.0.0.1, exactly what local dev needs) — a real deployment sets
# `DJANGO_ALLOWED_HOSTS=edmat.net,www.edmat.net,webek4.fuw.edu.pl` (or whatever the real domain(s)
# are) in /etc/apache2/envvars instead of this being hardcoded into a file every environment shares.
ALLOWED_HOSTS = _split_env_list('DJANGO_ALLOWED_HOSTS')

# The mirror image of the SECRET_KEY guard above: a real deployment that reached this file with
# only PART of its environment. `DEBUG=True` is correct and normal for local dev, where
# ALLOWED_HOSTS is empty and Django implicitly serves localhost only — that case is untouched. But
# DEBUG=True *together with* a real ALLOWED_HOSTS entry means someone set the hosts and not the
# debug flag, a half-applied production environment, which is precisely the state that would
# publish full tracebacks (SECRET_KEY, SQL, local paths) to anyone able to trigger an error on a
# public domain. Refuse to start instead.
if DEBUG and ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        f'DEBUG is True but DJANGO_ALLOWED_HOSTS is set to {ALLOWED_HOSTS!r}. That combination '
        'only happens when a production environment is half-applied, and it would serve full '
        'tracebacks — including SECRET_KEY and SQL — to anyone who can trigger an error on a '
        'public domain. Refusing to start. Set DJANGO_DEBUG=False in /etc/apache2/envvars.'
    )

# Empty by default — CSRF_TRUSTED_ORIGINS only matters once a real Host-header-spoofing-resistant
# origin check is needed (Django 4+, distinct from ALLOWED_HOSTS), which local dev over plain HTTP
# never hits. A real deployment sets `DJANGO_CSRF_TRUSTED_ORIGINS=https://edmat.net,https://www.edmat.net`.
CSRF_TRUSTED_ORIGINS = _split_env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Only for /sitemap.xml (config/sitemaps.py). It contributes no models and no migration — the
    # framework is a template renderer over the Sitemap classes we hand it, which is why it can be
    # added without touching the database.
    'django.contrib.sitemaps',
    # third-party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    # edmat apps — see CLAUDE.md Section 9 for the model/app split
    'taxonomy',
    'exercises',
    'materials',
    'community',
    'moderation',
    'study',
    'accounts',
    'notifications',
    'services',
    'messaging',
    'telemetry',
    'identity',
    'courses',
    # Booking sessions with a tutor — attaches to `services.Service` rather than being a marketplace
    # of its own, and hides behind the same `tutoring` feature flag. See booking/models.py.
    'booking',
    # One-off happenings people organise — a guest lecture, a workshop, an exam-prep meetup.
    # Deliberately its own app rather than a variant of courses or booking; see events/models.py
    # for why neither of those is the same shape.
    'events',
    # third-party — user-to-user messaging (see messaging/views.py for the thin DRF wrapper this
    # app builds over django-postman's own Message model/pm_write() API). django.contrib.sites
    # is genuinely required here, not optional despite postman's own doc comments suggesting
    # otherwise — postman.api unconditionally does `from django.contrib.sites.models import Site`
    # at module load time, and Django's own model metaclass raises a real RuntimeError the instant
    # that class is defined without 'django.contrib.sites' registered (confirmed directly, not
    # assumed — this failed with exactly that error before being added here).
    'django.contrib.sites',
    'postman',
]

SITE_ID = 1

# The public hostname /sitemap.xml builds its absolute URLs from — deliberately NOT the Site row
# SITE_ID points at above. That row exists only because django-postman requires the sites framework
# to be installed; nothing in this project ever set its domain, so it is whatever Django's own
# initial migration left there ('example.com' on a fresh database). A sitemap quietly full of
# example.com URLs is worse than no sitemap, so config/sitemaps.py reads this instead, and the Site
# row stays out of it. `EDMAT_PUBLIC_HOST` in the environment (see deploy/DEPLOYMENT.md) overrides
# it; the default is the real production domain, so a deployment that forgets to set it still emits
# correct URLs rather than broken ones.
EDMAT_PUBLIC_HOST = os.environ.get('EDMAT_PUBLIC_HOST', 'edmat.net')

# django-postman's own notify_users() would otherwise try to email a real EMAIL_BACKEND (Django's
# global default, unset here, is the SMTP backend, which would try to connect to localhost:25 and
# fail/hang — this project has no real email backend configured anywhere yet, the same honest gap
# LAUNCHCHECKLIST.md already flags for PasswordResetView). Our own thin API layer passes
# skip_notification=True to pm_write() specifically to avoid depending on this at all, but the
# console backend is set here too as a second, harmless safety net for any other codepath
# (e.g. the Django admin's own moderation actions) that might still call notify_users().
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # This close to the top so it wraps everything beneath it — a JSON list of 383 exercises or a
    # whole moderation queue is highly repetitive text, and the bytes saved are the largest single
    # win available on a link where the API and the SPA share one origin. Above the response cache
    # at the bottom of this list on purpose: what gets stored there is then the UNCOMPRESSED body,
    # so one cached entry serves both a client that accepts gzip and one that does not, and nothing
    # is ever compressed twice.
    #
    # Apache's own mod_deflate is configured separately at the vhost; the two overlap harmlessly,
    # because mod_deflate does not re-compress a response that already carries Content-Encoding.
    #
    # The BREACH caveat Django's own docs raise does not bite the surface that matters here: it
    # needs a secret and attacker-controlled text in the SAME compressed response, and this API's
    # one real secret (the DRF token) travels in a request header and is never echoed into a JSON
    # body. The one place a secret IS rendered into a body is the browsable API's own CSRF form
    # field, which is a staff/dev surface, not something a visitor is ever pointed at.
    'django.middleware.gzip.GZipMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Last on purpose: it reads `request.user`, which only exists once AuthenticationMiddleware
    # above has run, and it times the whole stack beneath it.
    'telemetry.middleware.RequestLogMiddleware',
    # Below the request log deliberately: a cache HIT is still a real request the telemetry (and so
    # the preload command's own picture of what is hot) must keep seeing — and the outer middlewares
    # (CORS headers included) still process the short-circuited response on the way out.
    'config.cachemw.AnonymousReadCacheMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Real, found-during-testing need, not a defensive default: SQLite only ever allows ONE
        # writer at a time, and Python's own sqlite3 module falls back to a 5-SECOND busy timeout
        # when nothing else is configured — genuinely too short under real concurrent write load.
        # A real multi-moderator concurrency test (two moderators approving different submissions
        # for the same course at nearly the same instant) reproduced `sqlite3.OperationalError:
        # database is locked` even for a single, tiny write statement, confirmed via the real dev
        # server's own log, not a guess. Raising this to 20s doesn't fix the underlying single-writer
        # limitation (that's inherent to SQLite, not this setting) — it just makes a genuinely
        # concurrent write WAIT for its turn instead of failing outright, which is the correct
        # tradeoff for this app's real write volume (a moderation queue, not a high-frequency system).
        'OPTIONS': {'timeout': 20},
    }
}

# --- Activity logs live in their own sharded SQLite files, never in db.sqlite3 ------------------
#
# Three separate reasons, all real:
#
# 1. **Blast radius.** A log table is by far the highest-volume writer in this app and the one with
#    the shortest useful life. Keeping it out of `default` means the corpus, the accounts and the
#    moderation record are never competing with it for SQLite's single writer lock, and never share
#    its backup or vacuum schedule.
# 2. **Deletion is a file operation.** Retention is a legal obligation, not a nice-to-have, and
#    `DELETE FROM` in SQLite doesn't return the disk — it needs a VACUUM that locks the database.
#    Sharding means whole files can eventually be dropped instead.
# 3. **Write concurrency.** SQLite allows one writer per FILE. N files means N concurrent writers.
#
# **Shard assignment is `user_id // LOG_SHARD_SIZE`, deliberately not `user_id % shard_count`.**
# That distinction is the whole design: integer division means shard membership NEVER changes as
# more shards are added, so growing capacity is "create another file", never "rewrite every row".
# Modulo would reshard the entire history every time the shard count changed.
#
# Anonymous traffic — the majority of requests on a public study site — cannot be sharded by a user
# it doesn't have, so it goes to its own dedicated file. That shard is the busiest by far, and is a
# real argument for splitting it by MONTH rather than by user later on; see LAUNCHCHECKLIST.md.
# How many reverse proxies sit in front of Django. Mirrors DRF's `NUM_PROXIES` below and is read by
# `telemetry.middleware.client_ip` for the same reason: only the rightmost `X-Forwarded-For` entries
# were written by our own Apache, everything to the left of them came from the caller.
#
# **Defaults to 0 — "trust nothing the caller sent, use REMOTE_ADDR" — and that default is
# load-bearing, not conservative boilerplate.** This was `1` until a real, reproduced bypass proved
# it wrong for the deployment this project actually has. `1` is only correct when a reverse proxy
# genuinely sits in front of Django and APPENDS its own value to `X-Forwarded-For`, which was true
# of the original stage-1 setup (Apache `ProxyPass` -> `runserver` on :8000, the arrangement the
# LAUNCHCHECKLIST's own first-deployment section describes). The real vhost
# (deploy/apache/edmat.conf) serves Django through **embedded mod_wsgi instead** — there is no
# proxy hop at all, Apache never writes an `X-Forwarded-For` header, and `REMOTE_ADDR` is already
# the true client. With hops=1, DRF and `client_ip` therefore read the rightmost entry of a header
# ONLY the caller could have set, so anyone could mint a fresh throttle bucket per request simply
# by rotating `X-Forwarded-For`. Measured directly against this codebase, not reasoned about: 15
# login attempts with a rotating forged header all returned 401 (zero throttling), against
# 10x401-then-429 for an honest client sending no header at all. It also let a caller forge the IP
# written into the audit log, which is worse than a missing log because it is a confident lie.
#
# Raise this to the real number of proxies ONLY if one is genuinely added in front of Django (a
# CDN, a load balancer, a re-introduced `ProxyPass`). Setting it above the real hop count re-opens
# exactly the bypass above, since the "trusted" entry it steps back to is then one the caller wrote.
EDMAT_TRUSTED_PROXY_HOPS = int(os.environ.get('EDMAT_NUM_PROXIES', '0'))

LOG_SHARD_SIZE = int(os.environ.get('EDMAT_LOG_SHARD_SIZE', '1000'))
LOG_SHARD_COUNT = int(os.environ.get('EDMAT_LOG_SHARD_COUNT', '8'))
LOG_ANON_SHARD = 'logs_anon'
LOG_DIR = Path(os.environ.get('EDMAT_LOG_DIR', BASE_DIR / 'logdata'))
LOG_DIR.mkdir(parents=True, exist_ok=True)


def _log_shard_db(name: str) -> dict:
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': LOG_DIR / f'{name}.sqlite3',
        # Same reasoning as `default` above — a log write must wait its turn rather than fail, since
        # a dropped log entry is a hole in an audit trail nobody notices until it matters.
        'OPTIONS': {'timeout': 20},
    }


for _shard_index in range(LOG_SHARD_COUNT):
    DATABASES[f'logs_{_shard_index}'] = _log_shard_db(f'logs_{_shard_index}')
DATABASES[LOG_ANON_SHARD] = _log_shard_db(LOG_ANON_SHARD)

DATABASE_ROUTERS = ['telemetry.routers.LogShardRouter']


# --- Cache: shared across processes, because the rate limits depend on it ------------------------
#
# This is a security setting wearing a performance setting's clothes. DRF counts every throttle
# through Django's cache, and with no `CACHES` configured at all Django falls back to `LocMemCache`
# — which is per-PROCESS, not shared. The real vhost runs `WSGIDaemonProcess ... processes=2`, so
# each worker would keep its own independent counters and every rate below would in practice be
# double what it says: `login: 10/min` would allow 20, and it would grow with any future worker
# count. That silently weakens the exact limits that exist to stop password guessing.
#
# `FileBasedCache` fixes it without adding an infrastructure dependency: a single directory on
# local disk, shared by every worker on the box, so one counter per key regardless of which process
# handles the request. Redis/Memcached would be the conventional answer and remain the right move
# if this ever runs on more than one machine (a file cache is shared per-host, not per-cluster) —
# but neither is installed here, and adding a whole daemon to make a throttle counter correct on a
# single-box deployment is a poor trade. `MAX_ENTRIES`/`CULL_FREQUENCY` are raised well above
# Django's 300-entry default specifically because throttle keys are numerous and short-lived: at
# the default, culling could evict a live counter and hand an attacker a fresh budget, which would
# reintroduce the very bypass this is here to close.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.environ.get('EDMAT_CACHE_DIR', str(BASE_DIR / 'cachedata')),
        'TIMEOUT': 300,
        'OPTIONS': {'MAX_ENTRIES': 10000, 'CULL_FREQUENCY': 4},
    }
}

# Redis, as an opt-in that changes nothing until a deployment exports one env var. The comment
# above said Redis "would be the conventional answer and remain the right move" — the owner made
# that move (2026-08): with `EDMAT_REDIS_URL` set, Django's own built-in Redis backend replaces the
# file cache (throttle counters become shared across every worker AND correct under any process
# count), the anonymous-read response cache (config/cachemw.py) becomes a genuinely shared cache
# rather than per-host, and notification delivery gains pub/sub push (notifications/redisbus.py).
# Unset — a fresh clone, setup.sh, this sandbox by default — everything keeps the file-cache
# behavior documented above, zero new daemons required.
EDMAT_REDIS_URL = os.environ.get('EDMAT_REDIS_URL', '')
if EDMAT_REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': EDMAT_REDIS_URL,
            'TIMEOUT': 300,
        }
    }

# ...except under the test runner, which gets a per-process cache instead. The whole point of the
# file cache above is that every process on the box shares it — and a test run is one of those
# processes. DRF counts throttle hits through the cache, so a suite run after somebody had been
# clicking around a dev server inherited that session's spent budget and failed with a real 429
# where the test expected a 401; and `cache.clear()` in a throttle test wiped the running server's
# counters in return. Both directions were live: the throttle tests passed alone and failed in a
# full run, which is the signature of shared state rather than a broken assertion. LocMem is
# per-process, so a run neither reads nor writes anybody else's counters.
if sys.argv[1:2] == ['test']:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Needed the moment DEBUG is False and a real webserver (not Django's own dev server) takes over
# serving static assets — the Django admin's and DRF's browsable-API's own CSS/JS, collected here by
# `manage.py collectstatic` and served directly by Apache (see deploy/apache/edmat.conf's own
# Alias /static/ directive) rather than through the WSGI app itself. Harmless in local dev — nothing
# reads this until `collectstatic` is actually run, which local dev never needs to.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# User-uploaded files (Material PDFs, Section 9) — served by Django's dev server only while DEBUG is
# on (config/urls.py wires static() for this); a real deployment fronts this with Apache directly
# instead (see deploy/apache/edmat.conf's own Alias /media/ directive) once DEBUG is False.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Material submission safety (materials/validators.py) — real content-type sniffing always runs
# regardless of these settings; a genuine ClamAV scan is attempted too, but this sandboxed dev
# environment has no ClamAV daemon installed (confirmed: no clamscan/clamdscan/freshclam binary
# anywhere, and no root access to install one — the same constraint CLAUDE.md's own venv note
# already records for a different tool). MATERIAL_SCAN_REQUIRED=False here is this environment's
# own honest default (an upload proceeds with the scan recorded as skipped, not silently treated as
# "scanned and clean") — a real deployment that actually runs ClamAV should set this True, which
# makes an unreachable scanner a hard rejection instead of a graceful skip.
MATERIAL_SCAN_REQUIRED = False
CLAMD_UNIX_SOCKET = '/var/run/clamav/clamd.ctl'
CLAMD_HOST = 'localhost'
CLAMD_PORT = 3310

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# ⚠️ Auth mechanism (CLAUDE.md Section 18, item 1) — resolved for this prototype as DRF's built-in
# TokenAuthentication: the "simple" option that section itself named, appropriate for a local/
# prototype deployment with no SSO requirement (Section 4). SessionAuthentication stays enabled too
# so the browsable API and the Django admin both keep working during development.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # JSON only in production; the browsable API is a DEVELOPMENT tool and stays one.
    #
    # Left unset, DRF enables `BrowsableAPIRenderer` unconditionally, which serves a full, rendered
    # HTML explorer for every endpoint to anyone who visits `/api/...` in a browser (that renderer
    # is selected by content negotiation on `Accept: text/html`, which is exactly what a browser
    # sends). On a public deployment that is a real, if unglamorous, problem: it publishes the
    # complete endpoint surface, every serializer's field names and types, and each view's own
    # docstrings; it renders write forms against endpoints the visitor may not be able to use; and
    # it is the one place `SessionAuthentication` and its CSRF enforcement are reachable from an
    # ordinary browser session, which is precisely the interaction that produced the registration
    # CSRF bug the LAUNCHCHECKLIST's own first-deployment section records. None of that is needed
    # by the real client: the SvelteKit frontend speaks JSON exclusively.
    #
    # Gated on DEBUG rather than removed outright so local development keeps the browsable API,
    # which is genuinely useful there and has been used throughout this project's own verification.
    'DEFAULT_RENDERER_CLASSES': (
        [
            'rest_framework.renderers.JSONRenderer',
            'rest_framework.renderers.BrowsableAPIRenderer',
        ]
        if DEBUG
        else ['rest_framework.renderers.JSONRenderer']
    ),
    # Phase 3 — deliberately no default pagination. Every real list endpoint the frontend actually
    # calls is already bounded by construction (course-scoped exercise/material lists, a `limit=`
    # top-rated/recent query, a moderator's own pending queue, one user's own exercise sets) — none
    # of them are the "browse an unbounded feed" shape pagination exists for. Turning it on here
    # would have meant every list response coming back wrapped in a {count,next,previous,results}
    # envelope, which the handful of custom @action endpoints (exercises/{id}/reviews/, /comments/,
    # /translations/, fields/{slug}/courses/, courses/{slug}/exercises/) never used anyway, since
    # each builds its own plain Response(serializer.data) — leaving pagination on globally would
    # just have meant a real, avoidable inconsistency between the two endpoint styles.
    'DEFAULT_PAGINATION_CLASS': None,
    # Rate limiting — a whole-project security scan found this app had NO throttling of any kind
    # anywhere, which meant `/api/auth/login/` accepted unlimited password guesses against any
    # account. `ScopedRateThrottle` is what lets an individual view opt into a tighter budget via its
    # own `throttle_scope` (registration, password reset, avatar upload); `accounts/throttles.py`
    # adds the two login-specific ones, which are applied directly on `LoginView` rather than
    # globally, since keying every request in the app on a submitted username makes no sense.
    #
    # DEPLOYMENT CAVEAT, real and worth not discovering the hard way: DRF throttling counts through
    # Django's cache, and this file configures no `CACHES` at all — so the default per-process
    # `LocMemCache` applies, and every worker in a multi-process deployment keeps its OWN counter,
    # multiplying every rate below by the worker count. Correct as-is for this prototype's
    # single-process dev server; a real deployment needs a shared cache (Redis/Memcached) before
    # these numbers mean what they say.
    # Left unset, DRF uses the WHOLE `X-Forwarded-For` header as the throttle key, so a caller
    # supplying their own gets a brand-new bucket on every request. `NUM_PROXIES` is what stops
    # that — but ONLY when it matches the real number of proxies, which for this deployment is
    # zero: the real vhost runs Django under embedded mod_wsgi, not behind a `ProxyPass`, so
    # nothing ever appends a trustworthy rightmost entry and `REMOTE_ADDR` is already the true
    # caller. `0` tells DRF to use `REMOTE_ADDR` and ignore the header entirely. See the full
    # writeup on `EDMAT_TRUSTED_PROXY_HOPS` above, including the measured bypass that a value of
    # `1` allowed here; both settings read the same env var so they can never disagree.
    'NUM_PROXIES': EDMAT_TRUSTED_PROXY_HOPS,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # The two global backstops are deliberately loose. This is a browse-heavy app — one exercise
        # detail page already fires several requests (the exercise, its reviews, its comments, the
        # author lookups), and the moderation page fires more than a dozen — so a tight global limit
        # would break ordinary reading long before it inconvenienced anyone abusive. These exist to
        # bound a runaway scraper, not to be the app's real security boundary; the scoped rates below
        # are where the actual protection lives.
        'anon': '600/hour',
        'user': '3000/hour',
        # Per-IP password guessing. 10/min is roughly 3x what a human fumbling a password does and
        # ~4 orders of magnitude below a useful brute-force rate.
        'login': '10/min',
        # Per-account, IP-independent — the credential-stuffing case a per-IP limit cannot see. Much
        # looser than the per-IP rate on purpose: this key is one an attacker who knows a victim's
        # email can deliberately exhaust to lock the real owner out, so it's sized to stop a
        # systematic search, not to punish typos. See accounts/throttles.py for the full reasoning.
        'login_username': '30/hour',
        'register': '10/hour',
        # `PasswordResetView` is still the honest always-200 stub Phase 2 shipped (no email backend
        # exists yet, Section 18 item 9), so there is nothing here to brute-force TODAY. Throttled
        # anyway, because the moment a real email backend lands this becomes an unauthenticated
        # endpoint that sends mail to an address the caller chooses — i.e. a spam relay — and the
        # limit is far easier to add now than to remember to add then.
        'password_reset': '5/hour',
        # Avatar upload is the most expensive authenticated write in the app: it decodes and
        # re-encodes a real image (accounts/avatar.py). 20/hour is far more than anyone genuinely
        # changing their profile picture needs, and low enough that the decode cost can't be used as
        # a CPU-exhaustion lever by a logged-in account.
        'avatar': '20/hour',
        # Material upload (`POST /api/material-submissions/`, wired onto the `create` action alone by
        # MaterialSubmissionViewSet.get_throttles). The most disk-expensive write in the app: up to
        # 25MB per request (`MAX_MATERIAL_SUBMISSION_SIZE_BYTES`), stored permanently, plus a
        # malware scan over every byte of it.
        #
        # 20/hour is picked against what a real contributor does rather than against a round number:
        # somebody uploading a semester's worth of past papers in one sitting might genuinely file a
        # dozen, and 20 leaves room for that without leaving the ceiling where it was. Before this
        # scope existed the only limit was the global `user` 3000/hour, which at 25MB a request is
        # tens of gigabytes an hour from one account; this brings the worst case to ~500MB/hour.
        #
        # That is still a lot, and deliberately so — this throttle bounds the RATE (and the scan CPU
        # that rides on it), while `Profile.material_upload_quota_bytes` is what bounds the TOTAL.
        # Neither substitutes for the other: a rate limit alone permits unbounded growth given time,
        # and a byte quota alone permits burning a whole allowance plus a scan queue in one second.
        'material_submission': '20/hour',
        # Address lookup proxies to Nominatim (OpenStreetMap), whose usage policy caps the WHOLE
        # application at 1 request/second. services/geocoding.py enforces that globally and caches
        # results for a day; this per-user scope is the second layer, so one account typing in the
        # location picker cannot spend the shared budget everyone else depends on. Generous enough
        # for real use — a search fires per submitted query, not per keystroke.
        'geocode': '60/hour',
    },
}

# CORS — the SvelteKit dev server (Phase 1 frontend) runs on a separate origin/port; this is what
# lets it call the API directly during Phase 3 wiring. Tightened to a real allowlist rather than
# CORS_ALLOW_ALL_ORIGINS, since credentials (the auth token) will ride along with these requests.
# A real deployment serves the built frontend from the SAME origin as the API (Apache's own vhost,
# see deploy/apache/edmat.conf) — a genuinely same-origin request never needs a CORS header at all,
# so this allowlist only ever matters there for the rare legitimate cross-origin case (a local dev
# frontend pointed at the real production API). `DJANGO_CORS_ALLOWED_ORIGINS` extends, rather than
# replaces, the dev list below — nothing to set for local dev, which keeps working unchanged.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
] + _split_env_list('DJANGO_CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True

# --- Real-TLS settings, gated behind one environment variable rather than hardcoded on ------------
# Deliberately NOT unconditionally True: this same settings.py has to keep working correctly during
# the deployment sequence's own earlier steps too (Apache running plain HTTP only, before certbot
# has actually issued a certificate) — flipping SECURE_SSL_REDIRECT on before a working TLS listener
# exists would mean every single request gets redirected to an HTTPS URL nothing is yet listening
# on, taking the whole site down. Set `EDMAT_HTTPS_READY=true` in the environment (the real
# systemd unit, once deploy/apache/edmat.conf's own TLS vhost is live and verified) to turn all of
# this on at once — see deploy/DEPLOYMENT.md for the exact moment this should flip.
_HTTPS_READY = os.environ.get('EDMAT_HTTPS_READY', 'false').lower() == 'true'

if _HTTPS_READY:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year — only after confirming HTTPS itself works end-to-end;
    # HSTS is a real, hard-to-undo browser-side commitment (see deploy/DEPLOYMENT.md's own note on
    # why this one specifically should be the LAST toggle flipped, not the first)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# --- Identity: sign-in provider drafts and the USOS ground ---------------------------------------
# Every one of these is deliberately empty. The `identity` app reads them at request time and
# reports what is missing (identity/providers.py's `blockers_for`, identity/usos.py's `_blockers`),
# which is what the frontend's connection modal renders — so configuring a real client here is what
# makes the UI stop describing that provider as a draft, with no copy to edit anywhere.
#
# Shape:
#   EDMAT_OAUTH_CLIENTS = {'google': {'client_id': '...', 'client_secret': '...'}, ...}
#   EDMAT_USOS_CREDENTIALS = {'uw': {'consumer_key': '...', 'consumer_secret': '...'}, ...}
#
# USOS credentials are keyed by school slug because USOS API issues them per institution, by that
# institution, after a request a person there approves — there is no global key, and pretending
# otherwise in the config shape would hide the real rollout cost.
EDMAT_OAUTH_CLIENTS: dict[str, dict[str, str]] = {}
EDMAT_USOS_CREDENTIALS: dict[str, dict[str, str]] = {}

# The public origin a provider would redirect back to. Until this exists there is no address to
# register as a callback, which is why it counts as a blocker in its own right.
EDMAT_OAUTH_REDIRECT_BASE = os.environ.get('EDMAT_OAUTH_REDIRECT_BASE', '')

# Swaps the USOS seam for a stand-in that answers like the real API (respecting granted scopes and
# per-installation capabilities) so the import, consent and standing paths are genuinely exercised
# by the test suite rather than merely plausible. Never a way to verify a real person: it talks to
# no university, and the UI says so wherever it is on.
EDMAT_USOS_MOCK = os.environ.get('EDMAT_USOS_MOCK', 'false').lower() == 'true'

# Linked from the sign-in connection modal — a draft is only honest if the reader can go and see
# what is actually planned (LAUNCHCHECKLIST.md §3a).
EDMAT_REPOSITORY_URL = os.environ.get(
    'EDMAT_REPOSITORY_URL', 'https://github.com/tryingtodosth/edmat'
)
