# Generated by Django 5.2.16 on 2026-07-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsuggestion',
            name='review_note',
            field=models.TextField(blank=True),
        ),
    ]
