# Generated by Django 5.2.16 on 2026-07-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_materialsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsubmission',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialsubmission',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='materialsubmission',
            name='price_currency',
            field=models.CharField(blank=True, default='PLN', max_length=3),
        ),
        migrations.AddField(
            model_name='materialsubmission',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
