# Generated by Django 5.2.16 on 2026-07-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0011_seed_material_uploads_verified_only_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsubmission',
            name='coverage',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
