# Generated by Django 5.2.16 on 2026-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0012_materialsubmission_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsubmission',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='materialsubmission',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
