# Generated by Django 5.2.16 on 2026-08-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0014_seed_classroom_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(choices=[('tutoring', 'Tutoring/services listings'), ('classroom', 'User-run courses'), ('messaging', 'User-to-user messaging'), ('exercise_submissions', 'New exercise submissions'), ('material_submissions', 'New material uploads'), ('material_uploads_verified_only', 'Material uploads: verified contributors only')], max_length=40, unique=True),
        ),
    ]
