# Generated by Django 5.2.16 on 2026-08-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0016_seed_events_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisesubmission',
            old_name='course',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='materialsubmission',
            old_name='course',
            new_name='branch',
        ),
    ]
