# Generated by Django 5.2.16 on 2026-08-08 19:06

import materials.validators
import moderation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0020_materialsubmission_file_reclaimed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsubmission',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='materialsubmission',
            name='file',
            field=models.FileField(blank=True, upload_to=moderation.models.material_submission_upload_path, validators=[materials.validators.validate_material_submission_file]),
        ),
    ]
