# Generated by Django 5.2.16 on 2026-08-26 15:35

from django.db import migrations, models


def seed_flag(apps, schema_editor):
    """The `issues` kill switch, on — a new feature arriving switched off would be indistinguishable
    from a broken one (0016's reasoning). Rides with the AlterField that admits the key, as 0016 did."""
    FeatureFlag = apps.get_model('moderation', 'FeatureFlag')
    FeatureFlag.objects.get_or_create(key='issues', defaults={'is_enabled': True})


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0021_materialsubmission_url_alter_materialsubmission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(choices=[('tutoring', 'Tutoring/services listings'), ('courses', 'User-run courses'), ('messaging', 'User-to-user messaging'), ('exercise_submissions', 'New exercise submissions'), ('material_submissions', 'New material uploads'), ('events', 'One-off events'), ('issues', 'Site issue reports'), ('material_uploads_verified_only', 'Material uploads: verified contributors only')], max_length=40, unique=True),
        ),
        migrations.RunPython(seed_flag, migrations.RunPython.noop),
    ]
