# Generated by Django 5.2.16 on 2026-08-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_solutionentry_solutionentryvote'),
        ('moderation', '0022_alter_featureflag_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsuggestion',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to='exercises.solutionentry'),
        ),
    ]
