# Generated by Django 5.2.16 on 2026-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0026_seed_posts_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsubmission',
            name='audience',
            field=models.CharField(choices=[('early_years', 'Early years (0–6, via an adult)'), ('primary', 'Primary school (6–12)'), ('secondary', 'Secondary school (12–19)'), ('university', 'University'), ('adult', 'Adult learners'), ('senior', 'Seniors'), ('all', 'Everyone')], default='university', max_length=12),
        ),
    ]
