# Generated by Django 5.2.16 on 2026-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0027_materialsubmission_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsubmission',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
