# Generated by Django 5.2.16 on 2026-09-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0028_alter_materialsubmission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(choices=[('tutoring', 'Tutoring/services listings'), ('courses', 'User-run courses'), ('messaging', 'User-to-user messaging'), ('exercise_submissions', 'New exercise submissions'), ('material_submissions', 'New material uploads'), ('events', 'One-off events'), ('issues', 'Site issue reports'), ('posts', 'Activity micro-posts'), ('chemistry', 'Chemistry drawings (Ketcher)'), ('material_uploads_verified_only', 'Material uploads: verified contributors only')], max_length=40, unique=True),
        ),
    ]
