# Generated by Django 5.2.16 on 2026-09-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0038_delete_materialsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(choices=[('tutoring', 'Tutoring/services listings'), ('courses', 'User-run courses'), ('messaging', 'User-to-user messaging'), ('exercise_submissions', 'New exercise submissions'), ('material_submissions', 'New material uploads'), ('events', 'One-off events'), ('issues', 'Site issue reports'), ('posts', 'Activity micro-posts'), ('chemistry', 'Chemistry drawings (Ketcher)'), ('material_uploads_verified_only', 'Material uploads: verified contributors only'), ('galleries', 'Picture galleries on content'), ('age_verification', 'Age gate on self-registration'), ('coauthoring', 'Co-authoring materials: versions, teams, proposals'), ('concepts', 'Concepts: wiki articles per audience')], max_length=40, unique=True),
        ),
    ]
