# The six conference kill switches (CONFERENCE-BRIEF.md §0): `venues`, `event_documents`,
# `tickets`, `shifts`, `cloakroom`, `role_preview` — the choices widened and the rows seeded ON in
# one migration, the safe-default posture every plain kill switch ships with. Seeding them on takes
# nothing away from anybody: there is no venue, document, ticket, shift or cloakroom item on the
# platform the moment this runs, so each flag's only effect on an existing deployment is that its
# surface exists at all. Seeded together so that the seven branches building the surfaces
# (CONFERENCE-BRIEF.md §4 rule 2) never each add a `moderation` migration and collide on the number.

# Generated by Django 5.2.16 on 2026-09-23 14:37

from django.db import migrations, models

KEYS = ['venues', 'event_documents', 'tickets', 'shifts', 'cloakroom', 'role_preview']


def seed_flags(apps, schema_editor):
    FeatureFlag = apps.get_model('moderation', 'FeatureFlag')
    for key in KEYS:
        FeatureFlag.objects.get_or_create(key=key, defaults={'is_enabled': True})


def unseed_flags(apps, schema_editor):
    apps.get_model('moderation', 'FeatureFlag').objects.filter(key__in=KEYS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0042_seed_sketches_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(choices=[('tutoring', 'Tutoring/services listings'), ('courses', 'User-run courses'), ('messaging', 'User-to-user messaging'), ('exercise_submissions', 'New exercise submissions'), ('material_submissions', 'New material uploads'), ('events', 'One-off events'), ('issues', 'Site issue reports'), ('posts', 'Activity micro-posts'), ('chemistry', 'Chemistry drawings (Ketcher)'), ('sketches', 'Freehand sketches (whiteboard)'), ('venues', 'Venues, rooms and checklists'), ('event_documents', 'Event documents and briefings'), ('tickets', 'Tickets, QR codes and scanning'), ('shifts', 'Volunteer rota (shifts)'), ('cloakroom', 'Cloakroom desk'), ('role_preview', 'View an event as a visitor'), ('material_uploads_verified_only', 'Material uploads: verified contributors only'), ('galleries', 'Picture galleries on content'), ('age_verification', 'Age gate on self-registration'), ('coauthoring', 'Co-authoring materials: versions, teams, proposals'), ('concepts', 'Concepts: wiki articles per audience')], max_length=40, unique=True),
        ),
        migrations.RunPython(seed_flags, unseed_flags),
    ]
