# The `school_demo` kill switch: the school-management demo published as a serverless page at
# /dziennik (HISTORY.md §17BO). Seeded ON, like every plain kill switch here, and for the usual
# reason — the surface does not exist before this runs, so switching it on takes nothing away.
#
# What it governs is unusual enough to state twice (the model says it too): this flag guards no
# Django endpoint. The demo has no backend on this site — the page is recorded answers baked into a
# static bundle the vhost serves — so the flag's whole effect is the two LINKS into it, in the user
# menu and the footer. Off hides the entrance; it does not take the page down, and a saved
# /dziennik URL keeps working. Removing the page means removing the Alias from the vhost.

# Generated by Django 5.2.16 on 2026-09-25 13:32

from django.db import migrations, models

KEY = 'school_demo'


def seed_flag(apps, schema_editor):
    FeatureFlag = apps.get_model('moderation', 'FeatureFlag')
    FeatureFlag.objects.get_or_create(key=KEY, defaults={'is_enabled': True})


def unseed_flag(apps, schema_editor):
    apps.get_model('moderation', 'FeatureFlag').objects.filter(key=KEY).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0044_management_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(choices=[('tutoring', 'Tutoring/services listings'), ('courses', 'User-run courses'), ('messaging', 'User-to-user messaging'), ('exercise_submissions', 'New exercise submissions'), ('material_submissions', 'New material uploads'), ('events', 'One-off events'), ('issues', 'Site issue reports'), ('posts', 'Activity micro-posts'), ('chemistry', 'Chemistry drawings (Ketcher)'), ('sketches', 'Freehand sketches (whiteboard)'), ('venues', 'Venues, rooms and checklists'), ('event_documents', 'Event documents and briefings'), ('tickets', 'Tickets, QR codes and scanning'), ('shifts', 'Volunteer rota (shifts)'), ('cloakroom', 'Cloakroom desk'), ('role_preview', 'View an event as a visitor'), ('organizations', 'Organisations'), ('tasks', 'Tasks on courses, events and materials'), ('needs', 'Needs board (help wanted)'), ('plans', 'Plans and roadmaps'), ('decisions', 'Decisions and polls'), ('work_dashboard', 'Personal work dashboard'), ('school_demo', 'School-management demo (/dziennik)'), ('material_uploads_verified_only', 'Material uploads: verified contributors only'), ('galleries', 'Picture galleries on content'), ('age_verification', 'Age gate on self-registration'), ('coauthoring', 'Co-authoring materials: versions, teams, proposals'), ('concepts', 'Concepts: wiki articles per audience')], max_length=40, unique=True),
        ),
        migrations.RunPython(seed_flag, unseed_flag),
    ]
