# Generated by Django 5.2.16 on 2026-09-20 07:17

import coauthoring.models
import django.db.models.deletion
import materials.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0018_material_body_translation_updated_at'),
        ('taxonomy', '0006_branch_proposed_at_branch_proposed_by_branch_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='pl', max_length=8)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('audience', models.CharField(choices=[('early_years', 'Early years (0–6, via an adult)'), ('primary', 'Primary school (6–12)'), ('secondary', 'Secondary school (12–19)'), ('university', 'University'), ('adult', 'Adult learners'), ('senior', 'Seniors'), ('all', 'Everyone')], default='university', max_length=12)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_currency', models.CharField(blank=True, choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='PLN', max_length=3)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('coverage', models.JSONField(blank=True, default=list)),
                ('seeking_coauthors', models.BooleanField(default=False)),
                ('seeking_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_projects', to='taxonomy.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_projects_created', to=settings.AUTH_USER_MODEL)),
                ('material', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='materials.material')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='coauthoring.materialproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('published', 'Published'), ('superseded', 'Superseded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=10)),
                ('kind', models.CharField(choices=[('file', 'A file'), ('link', 'A link'), ('body', 'Text written here')], default='file', max_length=5)),
                ('file', models.FileField(blank=True, upload_to=coauthoring.models.version_upload_path, validators=[materials.validators.validate_material_submission_file])),
                ('url', models.URLField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('change_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scan_status', models.CharField(choices=[('skipped', 'Not scanned'), ('clean', 'Scanned — clean'), ('flagged', 'Scanned — flagged')], default='skipped', max_length=10)),
                ('scan_detail', models.CharField(blank=True, max_length=200)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('file_reclaimed_at', models.DateTimeField(blank=True, null=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coauthoring.materialversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_versions', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='coauthoring.materialproject')),
            ],
            options={
                'ordering': ['project', 'number'],
                'constraints': [models.UniqueConstraint(fields=('project', 'number'), name='unique_version_number'), models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('project',), name='one_published_version_per_project')],
            },
        ),
        migrations.CreateModel(
            name='ProjectJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Waiting for a decision'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='coauthoring.materialproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_project_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('project', 'user'), name='one_pending_join_request')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('coauthor', 'Co-author')], default='coauthor', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='coauthoring.materialproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_member_per_project'), models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('project',), name='one_owner_per_project')],
            },
        ),
    ]
