# Generated by Django 5.2.16 on 2026-07-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicereview_servicewatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
