# Generated by Django 5.2.16 on 2026-07-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicereview_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivery_mode',
            field=models.CharField(choices=[('online', 'Online only'), ('in_person', 'In person only'), ('hybrid', 'Online or in person')], default='online', max_length=12),
        ),
        migrations.AddField(
            model_name='service',
            name='location_label',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
