# Generated by Django 5.2.16 on 2026-08-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_delivery_mode_service_location_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability_mode',
            field=models.CharField(choices=[('derived', 'Real availability, minus what is already taken'), ('declared', 'A fixed published window, whatever is already taken')], default='derived', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='session_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
