# Generated by Django 5.2.16 on 2026-08-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_availability_mode_service_session_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='courses',
            new_name='branches',
        ),
    ]
