# Generated by Django 5.2.16 on 2026-08-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='notify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taughtcourse',
            name='announce_new_lessons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taughtcourse',
            name='announce_new_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taughtcourse',
            name='discussion_mode',
            field=models.CharField(choices=[('off', 'No discussion'), ('participants', 'Participants and the instructor'), ('public', 'Anyone can read; participants can post')], default='participants', max_length=12),
        ),
    ]
