# Generated by Django 5.2.16 on 2026-08-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_backfill_course_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='taughtcourse',
            name='upload_quota_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taughtcourse',
            name='visibility',
            field=models.CharField(choices=[('only_you', 'Only you'), ('private', 'Private — only people you invite'), ('public', 'Public — anyone can find it')], default='only_you', max_length=12),
        ),
        migrations.AlterField(
            model_name='taughtcourse',
            name='status',
            field=models.CharField(choices=[('open', 'Open for enrolment'), ('running', 'Running, enrolment closed'), ('finished', 'Finished')], default='open', max_length=12),
        ),
    ]
