# Generated by Django 5.2.16 on 2026-09-17 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_url', models.URLField(max_length=500)),
                ('explanation', models.TextField()),
                ('good_faith_confirmed', models.BooleanField(default=False)),
                ('notifier_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('open', 'Open — awaiting review'), ('acted', 'Content removed or restricted'), ('rejected', 'Reviewed — no action taken')], default='open', max_length=10)),
                ('content_kind', models.CharField(blank=True, max_length=20)),
                ('content_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resolve_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_notices', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
