# Generated by Django 5.2.16 on 2026-08-27 18:53

import activity.models
import activity.postimage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0018_courseclaim_courseclaimimportancevote_and_more'),
        ('events', '0005_event_parent'),
        ('exercises', '0011_remove_exercisetranslation_hint_and_more'),
        ('materials', '0015_alter_materialcoverage_unique_together_and_more'),
        ('services', '0006_rename_courses_service_branches'),
        ('taxonomy', '0006_branch_proposed_at_branch_proposed_by_branch_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=activity.models.post_image_upload_path, validators=[activity.postimage.validate_activity_post_image])),
                ('is_removed', models.BooleanField(default=False)),
                ('auto_hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_posts', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='taxonomy.branch')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='taxonomy.discipline')),
                ('ref_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.course')),
                ('ref_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exercises.exercise')),
                ('ref_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='materials.material')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='exercises.tag')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('exercise', 'New exercise'), ('material', 'New material'), ('solution_entry', 'New solution/hint'), ('translation', 'New translation'), ('course', 'New course'), ('event', 'New event'), ('service', 'New tutoring listing'), ('post', 'New post'), ('review', 'New review'), ('claim', 'New claim'), ('comment', 'New comment')], max_length=20)),
                ('entry_kind', models.CharField(blank=True, max_length=10)),
                ('target_label', models.CharField(blank=True, max_length=300)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxonomy.branch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxonomy.discipline')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exercises.exercise')),
                ('happening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.event')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='materials.material')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='services.service')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('tags', models.ManyToManyField(blank=True, related_name='+', to='exercises.tag')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activity.post')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discipline__isnull', False), ('branch__isnull', True), ('tag__isnull', True)), models.Q(('discipline__isnull', True), ('branch__isnull', False), ('tag__isnull', True)), models.Q(('discipline__isnull', True), ('branch__isnull', True), ('tag__isnull', False)), _connector='OR'), name='post_exactly_one_anchor'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['kind', '-id'], name='activity_ac_kind_4b8f30_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['branch', '-id'], name='activity_ac_branch__58d4a5_idx'),
        ),
    ]
