# Generated by Django 5.2.16 on 2026-08-28 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_backfill_recent_history'),
        ('courses', '0018_courseclaim_courseclaimimportancevote_and_more'),
        ('exercises', '0011_remove_exercisetranslation_hint_and_more'),
        ('materials', '0015_alter_materialcoverage_unique_together_and_more'),
        ('taxonomy', '0006_branch_proposed_at_branch_proposed_by_branch_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='post_exactly_one_anchor',
        ),
        migrations.AddField(
            model_name='activityevent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxonomy.topic'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='taxonomy.topic'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discipline__isnull', False), ('branch__isnull', True), ('tag__isnull', True), ('topic__isnull', True)), models.Q(('discipline__isnull', True), ('branch__isnull', False), ('tag__isnull', True), ('topic__isnull', True)), models.Q(('discipline__isnull', True), ('branch__isnull', True), ('tag__isnull', False), ('topic__isnull', True)), models.Q(('discipline__isnull', True), ('branch__isnull', True), ('tag__isnull', True), ('topic__isnull', False)), _connector='OR'), name='post_exactly_one_anchor'),
        ),
    ]
