# Generated by Django 5.2.16 on 2026-09-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_remove_post_post_exactly_one_anchor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audience',
            field=models.CharField(choices=[('early_years', 'Early years (0–6, via an adult)'), ('primary', 'Primary school (6–12)'), ('secondary', 'Secondary school (12–19)'), ('university', 'University'), ('adult', 'Adult learners'), ('senior', 'Seniors'), ('all', 'Everyone')], db_index=True, default='university', max_length=12),
        ),
    ]
