# Generated by Django 5.2.16 on 2026-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='pl', max_length=8),
        ),
    ]
