# Generated by Django 5.2.16 on 2026-09-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='kind',
            field=models.CharField(choices=[('exercise', 'New exercise'), ('material', 'New material'), ('material_version', 'New material version'), ('solution_entry', 'New solution/hint'), ('translation', 'New translation'), ('course', 'New course'), ('event', 'New event'), ('service', 'New tutoring listing'), ('post', 'New post'), ('review', 'New review'), ('claim', 'New claim'), ('comment', 'New comment')], max_length=20),
        ),
    ]
