# Generated by Django 5.2.16 on 2026-09-23 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_material_version_kind'),
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='concepts.concept'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='kind',
            field=models.CharField(choices=[('exercise', 'New exercise'), ('material', 'New material'), ('material_version', 'New material version'), ('solution_entry', 'New solution/hint'), ('translation', 'New translation'), ('course', 'New course'), ('event', 'New event'), ('service', 'New tutoring listing'), ('post', 'New post'), ('review', 'New review'), ('claim', 'New claim'), ('comment', 'New comment'), ('concept', 'New concept'), ('concept_revision', 'New concept revision')], max_length=20),
        ),
    ]
