# Generated by Django 5.2.16 on 2026-07-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='taxonomy.topic')),
            ],
            options={
                'ordering': ['topic', 'order'],
                'unique_together': {('topic', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SubtopicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=300)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='taxonomy.subtopic')),
            ],
            options={
                'unique_together': {('subtopic', 'locale')},
            },
        ),
    ]
