# Generated by Django 5.2.16 on 2026-09-24 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coauthoring', '0003_fold_material_submissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(choices=[('open', 'Open — anyone may propose a change'), ('request', 'By request — ask to join, then edit'), ('closed', 'Closed — co-authors only')], default='open', max_length=10)),
                ('welcome_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coop', to='coauthoring.materialproject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cooperation settings',
                'verbose_name_plural': 'cooperation settings',
            },
        ),
    ]
