# Generated by Django 5.2.16 on 2026-09-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='area',
            field=models.CharField(blank=True, choices=[('core', 'Core (login, sessions, audit)'), ('logbook', 'Lesson logbook (attendance, topics, homework)'), ('grades', 'Grades and remarks'), ('homeroom', 'Homeroom and classification'), ('principal', 'Principal: substitutions, supervision, audit'), ('support', 'Psychological and pedagogical support'), ('registry', 'Registrar and administration'), ('student', 'Student account'), ('parent', 'Parent account'), ('messages', 'Messages and notifications'), ('school', 'After-school care, cafeteria, trips, library, nurse'), ('courses', 'Courses and materials (LMS)'), ('meetings', 'Video meetings'), ('compliance', 'Compliance pack'), ('demo', 'Demo mode and feedback')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='source',
            field=models.CharField(choices=[('site', 'The EdMat site'), ('school_demo', 'School-management demo')], db_index=True, default='site', max_length=20),
        ),
    ]
