# Generated by Django 5.2.16 on 2026-09-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_area_issue_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='area',
            field=models.CharField(blank=True, choices=[('core', 'Core (login, sessions, audit)'), ('logbook', 'Lesson logbook (attendance, topics, homework)'), ('grades', 'Grades and remarks'), ('homeroom', 'Homeroom and classification'), ('principal', 'Principal: substitutions, supervision, audit'), ('support', 'Psychological and pedagogical support'), ('registry', 'Registrar and administration'), ('student', 'Student account'), ('parent', 'Parent account'), ('messages', 'Messages and notifications'), ('school', 'After-school care, cafeteria, trips, library, nurse'), ('events', 'School events: open days, fetes, ceremonies'), ('courses', 'Courses and materials (LMS)'), ('meetings', 'Video meetings'), ('compliance', 'Compliance pack'), ('demo', 'Demo mode and feedback')], db_index=True, default='', max_length=20),
        ),
    ]
