# Generated by Django 5.2.16 on 2026-08-02 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0006_exerciserequirement_exerciserequirementvote'),
        ('materials', '0010_material_source_url'),
        ('taxonomy', '0002_subtopic_subtopictranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaughtCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for enrolment'), ('running', 'Running, enrolment closed'), ('finished', 'Finished')], default='draft', max_length=12)),
                ('enrollment_policy', models.CharField(choices=[('open', 'Anyone may join immediately'), ('approval', 'The instructor approves each request')], default='open', max_length=12)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('language', models.CharField(default='pl', max_length=8)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(blank=True, default='PLN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to='taxonomy.field')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, related_name='taught_courses', to='taxonomy.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('participant_notes', models.TextField(blank=True)),
                ('exercises', models.ManyToManyField(blank=True, related_name='lessons', to='exercises.exercise')),
                ('materials', models.ManyToManyField(blank=True, related_name='lessons', to='materials.material')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.taughtcourse')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting approval'), ('active', 'Taking part'), ('left', 'Left'), ('declined', 'Request declined'), ('removed', 'Removed by the instructor')], default='active', max_length=12)),
                ('request_note', models.CharField(blank=True, max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.taughtcourse')),
            ],
            options={
                'ordering': ['requested_at'],
                'constraints': [models.UniqueConstraint(fields=('course', 'participant'), name='unique_enrollment_per_course')],
            },
        ),
    ]
