# Generated by Django 5.2.16 on 2026-08-03 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_notify_taughtcourse_announce_new_lessons_and_more'),
        ('exercises', '0006_exerciserequirement_exerciserequirementvote'),
        ('materials', '0010_material_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taughtcourse',
            name='contribution_policy',
            field=models.CharField(choices=[('staff', 'Only the people running the course'), ('approval', 'Participants may submit; staff approve each one'), ('open', 'Participants may add directly, with no review')], default='approval', max_length=12),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('unlocks_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.taughtcourse')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('participant', 'Joins as a participant'), ('assistant', 'Joins as an assistant'), ('admin', 'Joins as an administrator')], default='participant', max_length=12)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='courses.taughtcourse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_invites_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Waiting for review'), ('approved', 'In the course'), ('rejected', 'Not accepted')], default='approved', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='courses.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.taughtcourse')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_contribution_decisions', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='exercises.exercise')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='materials.material')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('exercise__isnull', True), ('material__isnull', False)), models.Q(('exercise__isnull', False), ('material__isnull', True)), _connector='OR'), name='course_item_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('material__isnull', False)), fields=('course', 'material'), name='unique_material_per_course'), models.UniqueConstraint(condition=models.Q(('exercise__isnull', False)), fields=('course', 'exercise'), name='unique_exercise_per_course')],
            },
        ),
        migrations.CreateModel(
            name='CourseStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('assistant', 'Assistant')], default='assistant', max_length=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_staff_added', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='courses.taughtcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'user'), name='unique_staff_per_course'), models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('course',), name='unique_owner_per_course')],
            },
        ),
    ]
