# Generated by Django 5.2.16 on 2026-08-07 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_attachment_attachmentreview'),
        ('events', '0003_eventpost_eventpostlink_and_more'),
        ('exercises', '0007_alter_exercise_options_rename_course_exercise_branch_and_more'),
        ('materials', '0013_seed_material_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseitem',
            name='course_item_exactly_one_target',
        ),
        migrations.AddField(
            model_name='courseitem',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='courses.attachment'),
        ),
        migrations.AddField(
            model_name='courseitem',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='courseitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='events.event'),
        ),
        migrations.AddConstraint(
            model_name='courseitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attachment__isnull', True), ('event__isnull', True), ('exercise__isnull', True), ('material__isnull', False)), models.Q(('attachment__isnull', True), ('event__isnull', True), ('exercise__isnull', False), ('material__isnull', True)), models.Q(('attachment__isnull', False), ('event__isnull', True), ('exercise__isnull', True), ('material__isnull', True)), models.Q(('attachment__isnull', True), ('event__isnull', False), ('exercise__isnull', True), ('material__isnull', True)), _connector='OR'), name='course_item_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='courseitem',
            constraint=models.CheckConstraint(condition=models.Q(('lesson__isnull', True), ('chapter__isnull', True), _connector='OR'), name='course_item_one_filing_target'),
        ),
        migrations.AddConstraint(
            model_name='courseitem',
            constraint=models.UniqueConstraint(condition=models.Q(('attachment__isnull', False)), fields=('course', 'attachment'), name='unique_attachment_per_course'),
        ),
        migrations.AddConstraint(
            model_name='courseitem',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('course', 'event'), name='unique_event_per_course'),
        ),
    ]
