# Generated by Django 5.2.16 on 2026-08-07 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_courseitem_course_item_exactly_one_target_and_more'),
        ('exercises', '0007_alter_exercise_options_rename_course_exercise_branch_and_more'),
        ('study', '0003_exercisesetitem_include_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_links', to='study.exerciseset')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='courses.lesson')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_set_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonSetExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_set_links', to='exercises.exercise')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lessonexerciseset')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='lessonexerciseset',
            constraint=models.UniqueConstraint(condition=models.Q(('exercise_set__isnull', False)), fields=('lesson', 'exercise_set'), name='unique_set_per_lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonsetexercise',
            unique_together={('link', 'exercise')},
        ),
    ]
