# Generated by Django 5.2.16 on 2026-08-12 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_savedcomment'),
        ('courses', '0016_alter_attachment_file'),
        ('events', '0003_eventpost_eventpostlink_and_more'),
        ('exercises', '0007_alter_exercise_options_rename_course_exercise_branch_and_more'),
        ('materials', '0014_material_url_alter_material_file'),
        ('study', '0003_exercisesetitem_include_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseitem',
            name='course_item_exactly_one_target',
        ),
        migrations.AddField(
            model_name='courseitem',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='community.comment'),
        ),
        migrations.AddField(
            model_name='lessonexerciseset',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='courses.chapter'),
        ),
        migrations.AlterField(
            model_name='lessonexerciseset',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='courses.lesson'),
        ),
        migrations.AddConstraint(
            model_name='courseitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attachment__isnull', True), ('discussion__isnull', True), ('event__isnull', True), ('exercise__isnull', True), ('material__isnull', False)), models.Q(('attachment__isnull', True), ('discussion__isnull', True), ('event__isnull', True), ('exercise__isnull', False), ('material__isnull', True)), models.Q(('attachment__isnull', False), ('discussion__isnull', True), ('event__isnull', True), ('exercise__isnull', True), ('material__isnull', True)), models.Q(('attachment__isnull', True), ('discussion__isnull', True), ('event__isnull', False), ('exercise__isnull', True), ('material__isnull', True)), models.Q(('attachment__isnull', True), ('discussion__isnull', False), ('event__isnull', True), ('exercise__isnull', True), ('material__isnull', True)), _connector='OR'), name='course_item_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='courseitem',
            constraint=models.UniqueConstraint(condition=models.Q(('discussion__isnull', False)), fields=('course', 'discussion'), name='unique_discussion_per_course'),
        ),
        migrations.AddConstraint(
            model_name='lessonexerciseset',
            constraint=models.UniqueConstraint(condition=models.Q(('exercise_set__isnull', False)), fields=('chapter', 'exercise_set'), name='unique_set_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='lessonexerciseset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chapter__isnull', True), ('lesson__isnull', False)), models.Q(('chapter__isnull', False), ('lesson__isnull', True)), _connector='OR'), name='lesson_set_exactly_one_parent'),
        ),
    ]
