# Generated by Django 5.2.16 on 2026-07-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='Cleared on account deletion; the event itself is kept. Not an FK — cross-file.', null=True)),
                ('actor_label', models.CharField(blank=True, help_text='Username as it was at the time — a record of who acted survives a later rename.', max_length=150)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Registration'), ('password_change', 'Password change'), ('content_create', 'Content created'), ('content_edit', 'Content edited'), ('content_remove', 'Content removed'), ('upload', 'File uploaded'), ('moderation_decision', 'Moderation decision'), ('feature_flag', 'Feature flag changed'), ('permission_change', 'Permission or tier changed')], db_index=True, max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=60)),
                ('target_id', models.CharField(blank=True, max_length=60)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_id', 'created_at'], name='telemetry_a_actor_i_5d8774_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='Null for anonymous traffic. Not an FK — see the class docstring.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_truncated', models.BooleanField(default=False, help_text='True once the address has been cut to /24 (IPv4) or /48 (IPv6).')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_string', models.CharField(blank=True, max_length=500)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('request_id', models.CharField(db_index=True, max_length=36)),
                ('was_throttled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'status_code'], name='telemetry_r_created_d69e2e_idx')],
            },
        ),
    ]
