# Generated by Django 5.2.16 on 2026-09-23 15:01

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0010_contributions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('file', 'An uploaded file'), ('link', 'A link somewhere else')], default='file', max_length=8)),
                ('file', models.FileField(blank=True, upload_to=documents.models.document_upload_path)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=80)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('public', 'Anybody who can see the event'), ('attendees', 'People with a seat'), ('staff', 'Event staff'), ('organisers', 'Organisers only'), ('venue', 'The venue’s administrators')], default='staff', max_length=10)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('scanned', models.BooleanField(default=False)),
                ('scan_detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.event')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_documents_removed', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='documents.eventdocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['visibility', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='documents.eventdocument')),
            ],
            options={
                'ordering': ['-acknowledged_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='eventdocument',
            index=models.Index(fields=['event', 'visibility'], name='documents_e_event_i_65470c_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentacknowledgement',
            constraint=models.UniqueConstraint(fields=('document', 'user', 'version'), name='unique_document_acknowledgement'),
        ),
    ]
