# Generated by Django 5.2.16 on 2026-09-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0010_contributions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloakroomDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rack_labels', models.JSONField(blank=True, default=list)),
                ('opens_note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('open', 'Open — taking coats'), ('closed', 'Closed — reconciled')], default='open', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloakroom_desks_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloakroom_desks_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloakroom_desks', to='events.event')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CloakroomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_label', models.CharField(max_length=40)),
                ('token', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('stored', 'On the rack'), ('returned', 'Handed back against the token'), ('returned_by_exception', 'Handed back without the token, identity shown'), ('unclaimed', 'Still on the rack when the desk closed')], default='stored', max_length=24)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('deposited_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('exception_note', models.CharField(blank=True, max_length=300)),
                ('exception_identity_kind', models.CharField(choices=[('none', 'No identity shown'), ('student_card', 'Student card'), ('id_document', 'Identity document'), ('account', 'Signed-in EdMat account')], default='none', max_length=16)),
                ('deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloakroom_items_taken', to=settings.AUTH_USER_MODEL)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cloakroom.cloakroomdesk')),
                ('exception_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloakroom_exceptions_verified', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloakroom_items_returned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deposited_at', '-id'],
                'indexes': [models.Index(fields=['desk', 'token'], name='cloakroom_c_desk_id_47208f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'stored')), fields=('desk', 'token'), name='unique_stored_token_per_desk'), models.UniqueConstraint(condition=models.Q(('status', 'stored')), fields=('desk', 'rack_label'), name='unique_stored_rack_per_desk')],
            },
        ),
    ]
