# Generated by Django 5.2.16 on 2026-09-23 14:58

import django.db.models.deletion
import materials.validators
import venues.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0010_contributions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('event_kind_hint', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['venue__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('contact_note', models.TextField(blank=True)),
                ('security_phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('template_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_instances_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instances', to='events.event')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='venues.checklisttemplate')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instances', to='venues.venue')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_pl', models.CharField(max_length=300)),
                ('description_en', models.TextField(blank=True)),
                ('description_pl', models.TextField(blank=True)),
                ('owner_role', models.CharField(choices=[('organiser', 'The organiser'), ('venue', 'The building')], default='organiser', max_length=10)),
                ('due_offset_minutes', models.IntegerField(default=0)),
                ('anchor', models.CharField(choices=[('start', 'Before/after the event starts'), ('end', 'Before/after the event ends')], default='start', max_length=5)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('na_allowed', models.BooleanField(default=False)),
                ('evidence_kind', models.CharField(choices=[('none', 'Nothing — a tick is enough'), ('text', 'A short note'), ('link', 'A link'), ('file', 'A file')], default='none', max_length=5)),
                ('requires_venue_signoff', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='venues.checklisttemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('seated_capacity', models.PositiveSmallIntegerField(default=0)),
                ('fire_capacity', models.PositiveSmallIntegerField(default=0)),
                ('has_av', models.BooleanField(default=False)),
                ('accessible', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='venues.venue')),
            ],
            options={
                'ordering': ['venue__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='venues.venue'),
        ),
        migrations.CreateModel(
            name='VenueStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('porter', 'Porter')], default='administrator', max_length=14)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_staff_added', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_roles', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='venues.venue')),
            ],
            options={
                'ordering': ['added_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_pl', models.CharField(max_length=300)),
                ('description_en', models.TextField(blank=True)),
                ('description_pl', models.TextField(blank=True)),
                ('owner_role', models.CharField(choices=[('organiser', 'The organiser'), ('venue', 'The building')], default='organiser', max_length=10)),
                ('due_offset_minutes', models.IntegerField(default=0)),
                ('anchor', models.CharField(choices=[('start', 'Before/after the event starts'), ('end', 'Before/after the event ends')], default='start', max_length=5)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('na_allowed', models.BooleanField(default=False)),
                ('evidence_kind', models.CharField(choices=[('none', 'Nothing — a tick is enough'), ('text', 'A short note'), ('link', 'A link'), ('file', 'A file')], default='none', max_length=5)),
                ('requires_venue_signoff', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('computed_due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Not started'), ('in_progress', 'Being done'), ('done', 'Done'), ('not_applicable', 'Does not apply')], default='pending', max_length=14)),
                ('na_reason', models.TextField(blank=True)),
                ('evidence_text', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('evidence_file', models.FileField(blank=True, upload_to=venues.models.evidence_upload_path, validators=[materials.validators.validate_material_submission_file])),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items_done', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='venues.checklistinstance')),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['instance', 'status'], name='venues_chec_instanc_3d7484_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Withdrawn by the organiser')], default='requested', max_length=10)),
                ('expected_headcount', models.PositiveSmallIntegerField(default=0)),
                ('purpose', models.CharField(blank=True, max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings_decided', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='events.event')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings_requested', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.room')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
                'indexes': [models.Index(fields=['room', 'status', 'starts_at'], name='venues_room_room_id_252505_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='unique_room_name_per_venue'),
        ),
        migrations.AddConstraint(
            model_name='checklistinstance',
            constraint=models.UniqueConstraint(fields=('event', 'venue'), name='unique_checklist_per_event_venue'),
        ),
        migrations.AddConstraint(
            model_name='venuestaff',
            constraint=models.UniqueConstraint(fields=('venue', 'user'), name='unique_staff_per_venue'),
        ),
    ]
