# Generated by Django 5.2.16 on 2026-08-09 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('services', '0006_rename_courses_service_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_start'],
            },
        ),
        migrations.CreateModel(
            name='WeekScheduleWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='booking.weekschedule')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='services.service')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeekTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='weekschedule',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='booking.weektemplate'),
        ),
        migrations.CreateModel(
            name='WeekTemplateWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='services.service')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='booking.weektemplate')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='weektemplate',
            constraint=models.UniqueConstraint(fields=('tutor', 'name'), name='unique_week_template_name'),
        ),
        migrations.AddIndex(
            model_name='weekschedule',
            index=models.Index(fields=['tutor', 'week_start'], name='booking_wee_tutor_i_f9fdd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='weekschedule',
            constraint=models.UniqueConstraint(fields=('tutor', 'week_start'), name='unique_week_schedule'),
        ),
    ]
