# Generated by Django 5.2.16 on 2026-09-16 20:22

import chem.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_format', models.CharField(choices=[('ket', 'KET (Ketcher JSON)'), ('mol', 'MDL Molfile / RXN')], max_length=8)),
                ('source', models.TextField()),
                ('label', models.CharField(blank=True, max_length=300)),
                ('image', models.FileField(upload_to=chem.models.drawing_upload_path)),
                ('image_kind', models.CharField(choices=[('svg', 'SVG'), ('raster', 'WebP')], max_length=6)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chem_drawings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
