#!/usr/bin/env node
/* build-static.js — assemble the serverless build served at edmat.net/dziennik.
 *
 *   node scripts/build-static.js [--out dist-static] [--base /dziennik]
 *
 * Takes `public/` plus the recorded `demo-snapshot.json` and produces a directory of plain files
 * that Apache can hand out with no process behind them. Three things the real server generates on
 * the fly have to be produced here instead, and they are the whole of what this script does beyond
 * copying:
 *
 *   /app/screens.js    the server concatenates `public/app/screens/*.js` per request and prefixes
 *                      it with the module map; here it is written once.
 *   window.EDMAT_BASE  the server serves `/app/base.js`; here it is inlined into index.html, so
 *                      the page needs one fewer round trip and cannot race it.
 *   /app/autoprint.js  a one-liner the server returns inline.
 *
 * Two things are deliberately NOT copied:
 *
 *   sw.js              the service worker caches API responses for offline use. There is no server
 *                      to be offline from, and a cache from an earlier visit answering over the
 *                      snapshot is a silent wrong answer. `snapshot.js` also unregisters any worker
 *                      a previous visit left behind — dropping the file alone would not.
 *   app/screens/       the individual screen files, now inside screens.js. Shipping both would
 *                      double the payload and leave two copies to disagree.
 *
 * The snapshot is emitted as JavaScript, not JSON, on purpose: a .json would have to be fetched,
 * and the promise made about this page is that exactly one request leaves the browser — the issue
 * report. A script tag is not a request the page makes; it is the page.
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const modules = require('../server/modules');

const ROOT = path.join(__dirname, '..');
const argv = process.argv.slice(2);
const arg = (n, d) => { const a = argv.find((x) => x.startsWith('--' + n + '=')); return a ? a.split('=').slice(1).join('=') : d; };
const OUT = path.resolve(ROOT, arg('out', 'dist-static'));
const BASE = arg('base', '/dziennik').replace(/\/+$/, '');
const SNAPSHOT = path.resolve(ROOT, arg('snapshot', 'public/demo-snapshot.json'));
const PUBLIC = path.join(ROOT, 'public');

const SKIP_TOP = new Set(['sw.js', 'demo-snapshot.json']);

function copyDir(from, to, rel) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const r = rel ? rel + '/' + entry.name : entry.name;
    if (!rel && SKIP_TOP.has(entry.name)) continue;
    if (r === 'app/screens') continue;                 // folded into app/screens.js
    const src = path.join(from, entry.name), dst = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dst, r);
    else fs.copyFileSync(src, dst);
  }
}

function main() {
  if (!fs.existsSync(SNAPSHOT)) {
    console.error(`No snapshot at ${path.relative(ROOT, SNAPSHOT)} — run: node scripts/record-snapshot.js`);
    process.exit(2);
  }
  fs.rmSync(OUT, { recursive: true, force: true });
  copyDir(PUBLIC, OUT, '');

  // --- app/screens.js (what the server builds per request) -------------------------------------
  const screensDir = path.join(PUBLIC, 'app', 'screens');
  const screenFiles = fs.readdirSync(screensDir).filter((f) => f.endsWith('.js')).sort();
  const enabled = {};
  for (const m of modules.MODULES) enabled[m.id] = true;   // a published demo shows the whole product
  const screensJs = `window.EdApp.setModules(${JSON.stringify(enabled)});\n`
    + screenFiles.map((f) => `/* ${f} */\n` + fs.readFileSync(path.join(screensDir, f), 'utf8')).join('\n;\n');
  fs.writeFileSync(path.join(OUT, 'app', 'screens.js'), screensJs);

  // --- app/autoprint.js -------------------------------------------------------------------------
  fs.writeFileSync(path.join(OUT, 'app', 'autoprint.js'),
    "if (location.search.indexOf('print=1') >= 0) window.addEventListener('load', function () { window.print(); });\n");

  // --- app/demo-snapshot.js ---------------------------------------------------------------------
  const snap = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
  fs.writeFileSync(path.join(OUT, 'app', 'demo-snapshot.js'),
    '/* Recorded answers. Generated by scripts/record-snapshot.js — do not edit by hand. */\n'
    + 'window.__EDMAT_SNAPSHOT__ = ' + JSON.stringify(snap) + ';\n');

  // --- neutralise every path to the network, in the shipped bytes -------------------------------
  // Not "guarded so it cannot be reached" but "not there to reach". `core.js` returns through
  // EdSnapshot before its `fetch` and `print.js`'s probe would only ever 404 here, so both are dead
  // code in this build — but dead code on a published page is still code somebody has to reason
  // about, and a future edit above the guard would wake it up. Removing it makes the promise a
  // property of the file rather than of an argument about control flow.
  const corePath = path.join(OUT, 'app', 'core.js');
  let core = fs.readFileSync(corePath, 'utf8');
  const CORE_FETCH = 'var res = await fetch(BASE + path, { method: method, credentials: \'same-origin\', headers: body != null ? { \'Content-Type\': \'application/json\' } : {}, body: body != null ? JSON.stringify(body) : undefined });';
  if (!core.includes(CORE_FETCH)) throw new Error('core.js rawFetch no longer matches what build-static.js strips — check the seam before publishing.');
  core = core.replace(CORE_FETCH,
    '/* The network call is removed in the static build: EdSnapshot answers every request above. */\n'
    + '    throw new Error(\'no backend in the static demo build\');');
  fs.writeFileSync(corePath, core);

  // `print.js` asks the server whether it can render a PDF, and then opens a server-rendered
  // document. Neither exists here, so the whole module is replaced by a stub that says so instead
  // of opening a tab onto a 404. Replaced wholesale rather than patched: what is wanted is not a
  // probe that always answers "no" but a print button that is honest about this build.
  fs.writeFileSync(path.join(OUT, 'app', 'print.js'),
    `/* Static demo build: there is no server to render a PDF or serve a print-ready page.
`
    + ` * Generated by scripts/build-static.js — the real module is public/app/print.js. */
`
    + `(function () {
`
    + `  var A = window.EdApp; if (!A) return;
`
    + `  var MSG = { pl: 'Wydruki są dostępne w pełnej wersji — to zapisane demo bez serwera.',\n`
    + `              en: 'Printing is available in the full version — this is a recorded, serverless demo.' };
`
    + `  function say() { try { A.toast(MSG[(window.EdI18n && EdI18n.get()) === 'en' ? 'en' : 'pl'], 'warning'); } catch (e) {} return Promise.resolve(false); }
`
    + `  A.openPrint = say; A.pdfAvailable = function () { return Promise.resolve(false); };
`
    + `})();
`);

  // --- index.html -------------------------------------------------------------------------------
  const indexPath = path.join(OUT, 'index.html');
  let html = fs.readFileSync(indexPath, 'utf8');
  const inject = `<script>window.EDMAT_BASE=${JSON.stringify(BASE)};</script>\n`
    + '<script src="app/demo-snapshot.js"></script>\n'
    + '<script src="app/snapshot.js"></script>\n';
  /* Polish by default, regardless of the browser's language.
     `app/i18n.js` falls back to `navigator.language`, which is right for a product a school
     installs on its own machines and wrong for a page published on a Polish site: a visitor whose
     browser is set to English would meet a Polish school's logbook in English. Seeded into
     localStorage BEFORE i18n.js runs (it reads the stored value first), and only when nothing is
     stored and no `?lang=` was asked for — so the in-app switcher and an explicit link still win,
     and a returning visitor keeps whatever they chose. Matches the site around it, whose own base
     locale is `pl`. */
  const PL_DEFAULT = '<script>try{if(!localStorage.getItem("edmat.locale")&&!/[?&#]lang=(pl|en)\\b/.test(location.hash+location.search))localStorage.setItem("edmat.locale","pl")}catch(e){}</script>\n';
  if (!html.includes('<script src="app/i18n.js"></script>')) throw new Error('index.html no longer loads app/i18n.js — the Polish default is injected ahead of it');
  html = html.replace('<script src="app/i18n.js"></script>', PL_DEFAULT + '<script src="app/i18n.js"></script>');

  if (!html.includes('app/core.js')) throw new Error('index.html no longer loads app/core.js — build-static.js injects ahead of it');
  html = html.replace('<script src="app/core.js"></script>', inject + '<script src="app/core.js"></script>');
  // The manifest's start_url has to follow the page under its prefix, or "add to home screen"
  // lands on the site root instead of the demo.
  html = html.replace('<link rel="manifest" href="manifest.webmanifest">', `<link rel="manifest" href="${BASE}/manifest.webmanifest">`);
  fs.writeFileSync(indexPath, html);

  // --- manifest ---------------------------------------------------------------------------------
  const manifestPath = path.join(OUT, 'manifest.webmanifest');
  if (fs.existsSync(manifestPath)) {
    const m = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    m.start_url = BASE + '/'; m.scope = BASE + '/';
    /* Icon paths are root-absolute in the source manifest, which is right when the demo owns the
       whole origin and wrong the moment it is a subdirectory of somebody else's site: `/icon.svg`
       would resolve to edmat.net's own icon, or to a 404. Found by looking at the browser console
       on the first static run — it is the only thing the page complained about. */
    if (Array.isArray(m.icons)) {
      m.icons = m.icons.map((icon) => (
        icon && typeof icon.src === 'string' && icon.src.startsWith('/') && !icon.src.startsWith(BASE + '/')
          ? Object.assign({}, icon, { src: BASE + icon.src })
          : icon
      ));
    }
    fs.writeFileSync(manifestPath, JSON.stringify(m, null, 2));
  }

  // --- refuse a build that would still try to reach a server -------------------------------------
  // The promise this build makes is one outbound request. Assert it rather than trust it: the only
  // `fetch(` left in shipped app code must be snapshot.js's forward to /api/issues/.
  const offenders = [];
  for (const f of ['app/core.js', 'app/print.js', 'app/report-issue.js', 'app/shell.js', 'app/screens.js']) {
    const body = fs.readFileSync(path.join(OUT, f), 'utf8');
    const n = (body.match(/\bfetch\s*\(/g) || []).length;
    if (n) offenders.push(`${f}: ${n}`);
  }
  const snapBody = fs.readFileSync(path.join(OUT, 'app', 'snapshot.js'), 'utf8');
  const snapFetches = (snapBody.match(/\bfetch\s*\(/g) || []).length;

  const bytes = (p) => fs.statSync(p).size;
  console.log(`built ${path.relative(ROOT, OUT)} (base ${BASE})`);
  console.log(`  screens.js       ${Math.round(bytes(path.join(OUT, 'app', 'screens.js')) / 1024)} KB (${screenFiles.length} screens)`);
  console.log(`  demo-snapshot.js ${Math.round(bytes(path.join(OUT, 'app', 'demo-snapshot.js')) / 1024)} KB (${(snap.logins || []).length} roles)`);
  console.log(`  sw.js            not shipped (stale cache would answer over the snapshot)`);
  console.log(`  fetch( in snapshot.js: ${snapFetches} (expected 1 — the issue report)`);
  if (offenders.length) {
    console.error('  ERROR: shipped app code still calls fetch() directly: ' + offenders.join(', '));
    console.error('  Every request must go through core.js rawFetch so EdSnapshot can answer it.');
    process.exit(1);
  }
  if (snapFetches !== 1) {
    console.error(`  ERROR: snapshot.js makes ${snapFetches} fetch calls; exactly 1 (the issue report) is allowed.`);
    process.exit(1);
  }
}

main();
