# Generated by Django 5.2.16 on 2026-08-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment_auto_hidden_at_review_auto_hidden_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='removed_by_author',
            field=models.BooleanField(default=False),
        ),
    ]
