# Generated by Django 5.2.16 on 2026-09-23 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0010_contributions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('door', 'Door / entrance'), ('room', 'Session room'), ('info', 'Information desk'), ('cloakroom', 'Cloakroom'), ('runner', 'Runner'), ('setup', 'Set-up / tear-down'), ('other', 'Other')], default='other', max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('location_text', models.CharField(blank=True, max_length=300)),
                ('briefing_note', models.TextField(blank=True)),
                ('minors_permitted', models.BooleanField(default=False)),
                ('requires_adult', models.BooleanField(default=False)),
                ('needs_confirmation', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='events.event')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='events.session')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('needed', models.PositiveSmallIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('follows_session', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shifts.station')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('consent_note', models.CharField(blank=True, max_length=300)),
                ('vetting_checked_at', models.DateTimeField(blank=True, null=True)),
                ('vetting_reference', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_consents_recorded', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_records', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('claimed', 'Claimed'), ('confirmed', 'Confirmed'), ('dropped', 'Dropped'), ('no_show', 'No show'), ('done', 'Done')], default='claimed', max_length=10)),
                ('source', models.CharField(choices=[('self', 'Claimed by the volunteer'), ('organiser', 'Assigned by an organiser'), ('pool', 'Picked up from the pool')], default='self', max_length=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('drop_reason', models.CharField(blank=True, max_length=200)),
                ('hours_credited', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credit_note', models.CharField(blank=True, max_length=300)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments_confirmed', to=settings.AUTH_USER_MODEL)),
                ('credited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments_credited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shift')),
            ],
            options={
                'ordering': ['shift__starts_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'dropped'), _negated=True), fields=('shift', 'user'), name='unique_live_assignment_per_shift')],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['station', 'starts_at'], name='shifts_shif_station_effeec_idx'),
        ),
        migrations.AddConstraint(
            model_name='volunteerrecord',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_volunteer_record_per_event'),
        ),
    ]
