# Generated by Django 5.2.16 on 2026-07-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_exerciseset_slug_and_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesetitem',
            name='include_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercisesetitem',
            name='include_hint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercisesetitem',
            name='include_solution',
            field=models.BooleanField(default=False),
        ),
    ]
