# Generated by Django 5.2.16 on 2026-07-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('type', models.CharField(choices=[('script', 'Course script'), ('exam_collection', 'Exam collection'), ('midterm_collection', 'Midterm collection'), ('exercise_collection', 'Exercise collection'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='materials/')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='taxonomy.course')),
                ('topics', models.ManyToManyField(blank=True, related_name='materials', to='taxonomy.topic')),
            ],
            options={
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='MaterialTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='materials.material')),
            ],
            options={
                'unique_together': {('material', 'locale')},
            },
        ),
    ]
