# Generated by Django 5.2.16 on 2026-07-25 17:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('taxonomy', '0002_subtopic_subtopictranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='topics',
        ),
        migrations.CreateModel(
            name='MaterialCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='materials.material')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_coverage', to='taxonomy.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_coverage', to='taxonomy.topic')),
            ],
            options={
                'ordering': ['topic', 'subtopic'],
                'unique_together': {('material', 'topic', 'subtopic')},
            },
        ),
        migrations.CreateModel(
            name='MaterialCoverageVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Agree'), (-1, 'Disagree')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='materials.materialcoverage')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coverage', 'voter')},
            },
        ),
    ]
