# Generated by Django 5.2.16 on 2026-07-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_tagfollow'),
        ('materials', '0002_remove_material_topics_materialcoverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='materials', to='exercises.tag'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('script', 'Course script'), ('exam_collection', 'Exam collection'), ('midterm_collection', 'Midterm collection'), ('exercise_collection', 'Exercise collection'), ('formula_sheet', 'Formula sheet'), ('lecture_slides', 'Lecture slides'), ('solution_guide', 'Solution guide'), ('syllabus', 'Syllabus'), ('practice_test', 'Practice test'), ('recording', 'Recorded lecture'), ('textbook_excerpt', 'Textbook excerpt'), ('code_dataset', 'Code / dataset'), ('other', 'Other')], max_length=20),
        ),
    ]
