# Generated by Django 5.2.16 on 2026-07-26 20:28

import materials.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_tags_alter_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='materials/', validators=[materials.validators.validate_material_submission_file]),
        ),
    ]
