# Generated by Django 5.2.16 on 2026-07-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_material_estimated_minutes_material_price_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='PLN', max_length=3),
        ),
    ]
