# Generated by Django 5.2.16 on 2026-07-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_material_submitted_by_materialrequirementvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequirement',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
