# Generated by Django 5.2.16 on 2026-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_materialrequirement_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
