# Generated by Django 5.2.16 on 2026-08-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_material_source_url'),
        ('taxonomy', '0004_branch_drop_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['branch', 'order']},
        ),
        migrations.RenameField(
            model_name='material',
            old_name='course',
            new_name='branch',
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('branch', 'slug')},
        ),
    ]
