# Generated by Django 5.2.16 on 2026-08-08 19:06

import materials.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_seed_material_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='materials/', validators=[materials.validators.validate_material_submission_file]),
        ),
    ]
