# Generated by Django 5.2.16 on 2026-08-25 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_material_url_alter_material_file'),
        ('taxonomy', '0006_branch_proposed_at_branch_proposed_by_branch_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialcoverage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='materialcoverage',
            name='kind',
            field=models.CharField(choices=[('covers', 'Covers'), ('requires', 'Requires')], default='covers', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='materialcoverage',
            unique_together={('material', 'kind', 'topic', 'subtopic')},
        ),
        migrations.CreateModel(
            name='MaterialCoverageImportanceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'More important'), (-1, 'Less important')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importance_votes', to='materials.materialcoverage')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coverage', 'voter')},
            },
        ),
    ]
