# Generated by Django 5.2.16 on 2026-09-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_alter_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materialtranslation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
