# Generated by Django 5.2.16 on 2026-07-23 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('published', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('original_locale', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='taxonomy.course')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(blank=True, related_name='exercises', to='taxonomy.topic')),
                ('tags', models.ManyToManyField(blank=True, related_name='exercises', to='exercises.tag')),
            ],
            options={
                'ordering': ['course', 'number'],
                'unique_together': {('course', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exercises', 'Exercise sheet'), ('midterm', 'Midterm'), ('exam', 'Exam'), ('other', 'Other')], max_length=10)),
                ('collection', models.CharField(blank=True, max_length=200)),
                ('original_problem_number', models.PositiveIntegerField(blank=True, null=True)),
                ('pages', models.CharField(blank=True, max_length=20)),
                ('chapter', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSourceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=8)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='exercises.exercisesource')),
            ],
            options={
                'unique_together': {('source', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=300)),
                ('statement', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('pending', 'Pending review'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='exercises.exercise')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('translated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exercise', 'locale'],
                'unique_together': {('exercise', 'locale', 'status')},
            },
        ),
    ]
