# Generated by Django 5.2.16 on 2026-07-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='auto_hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
