# Generated by Django 5.2.16 on 2026-07-26 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_tagfollow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercisetranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='exercisetranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('exercise', 'locale'), name='one_published_translation_per_locale'),
        ),
    ]
