# Generated by Django 5.2.16 on 2026-07-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_partial_unique_published_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
