# Generated by Django 5.2.16 on 2026-08-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_exerciserequirement_exerciserequirementvote'),
        ('taxonomy', '0004_branch_drop_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['branch', 'number']},
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='course',
            new_name='branch',
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('branch', 'number')},
        ),
    ]
