# Generated by Django 5.2.16 on 2026-08-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_migrate_hints_solutions_to_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetranslation',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='exercisetranslation',
            name='solution',
        ),
    ]
