# Generated by Django 5.2.16 on 2026-09-20 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_audience'),
        # Pinned to the last MERGED materials migration rather than the autodetector's
        # `__latest__` pick: this only needs the `materials_material` table to exist, and naming a
        # migration that is still in flight on another branch would make this one unappliable if
        # the two land separately.
        ('materials', '0017_alter_material_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMaterialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('source', 'In this material'), ('practice', 'Practises this material')], default='source', max_length=10)),
                ('locator', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_links', to='exercises.exercise')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_links', to='materials.material')),
            ],
            options={
                'ordering': ['material', 'created_at'],
                'unique_together': {('exercise', 'material')},
            },
        ),
    ]
